### ISSUE TITLE
Restore from Backup Instructions

### ISSUE THREAD

**Issue by CharleyPeng1** [kobotoolbox/kobo-docker#110]
It would be great to see instructions on how to restore from backup.

**Comment by esmail** [comment]
Agreed; I'll try to work this into the README shortly. Note to self:
```bash
root@postgres:/# su postgres -c "pg_restore --file=/srv/backups/$(ls -t /srv/backups/ | head -n1))"
```

**Comment by iahmedani** [comment]
is there any progress??

**Comment by janknobloch** [comment]
MEDIA

sudo tar xpf /PATH/TO/kobo-docker/backups/kobocat/BACKUP_FILENAME.tar -C /PATH/TO/kobo-docker/.vols/kobocat_media_uploads/ --strip-components=1

POSTGRES RESTORE:

mkdir /home/knobloch/kobo-docker/.vols/db/backup

cp /home/knobloch/kobo-docker/backups/postgres/postgres_backup___2018.09.12.11_59.pg_restore /home/knobloch/kobo-docker/.vols/db/backup/restore.pgdump

docker exec kobodocker_postgres_1 bash -c "pg_restore --verbose --clean --no-acl --no-owner -h localhost -U kobo -d kobotoolbox /srv/db/backup/restore.pgdump"

MONGO RESTORE:

mkdir /home/knobloch/kobo-docker/.vols/mongo/backups

sudo tar xfvz /PATH/TO/kobo-docker/backups/mongo/mongo_backup__2018.09.12.11_59.mongorestore.tar.gz -C /PATH/TO/kobo-docker/.vols/mongo/backups/

sudo docker exec kobodocker_mongo_1 bash -c "cd /srv/db/backups && mongorestore"

Hope this helps.

**Comment by noliveleger** [comment]
Backups instructions are available from [README](https://github.com/kobotoolbox/kobo-docker/blob/master/README.md). 
https://github.com/kobotoolbox/kobo-docker#backups
