### ISSUE TITLE
Mongo `add_index.sh` not running(?)

### ISSUE THREAD

**Issue by jnm** [kobotoolbox/kobo-docker#113]
In the `mongo` shell on a recently created stack:
```
> use formhub;
switched to db formhub
> db.instances.getIndexes();
[
	{
		"v" : 1,
		"key" : {
			"_id" : 1
		},
		"name" : "_id_",
		"ns" : "formhub.instances"
	}
]
> 
```
I'd expect that there'd be a [`_userform_id` index](https://github.com/kobotoolbox/kobo-docker/blob/9905f1f1e766c6e33eb43baf9bc7da36125c765d/base_images/mongo/add_index.sh), but there isn't. If I do
```
root@mongo:/# bash /srv/add_index.sh 
```
inside the Mongo container, the index is created.

**Comment by noliveleger** [comment]
Seems to be fixed since mongo use new image and new scripts to start.
