### ISSUE TITLE
Error in Enketo

### ISSUE THREAD

**Issue by iahmedani** [kobotoolbox/kobo-docker#114]
Dear Team,

with the recent update, I'm getting following error on few of my forms. 
> Enketo error, reason: ('Connection aborted.', gaierror(-5, 'No address associated with hostname'))

**Comment by esmail** [comment]
If using the `server` setup, you might need to set up the [`extra_hosts`](https://github.com/kobotoolbox/kobo-docker/blob/9905f1f1e766c6e33eb43baf9bc7da36125c765d/docker-compose.server.yml#L182) directives as mentioned step 11 of the README.

**Comment by devisbal** [comment]
On a public host:
Instead of that, what I did was to add on /etc/hosts the servers name pointing to 127.0.0.1:
On /etc/hosts added the IP and the external hostname:
Example:
127.0.0.1 kc.proyecto.com
127.0.0.1 kf.proyecto.com
127.0.0.1 ek.proyecto.com

I'm wondering if this is OK, or should I go with the extra_hosts directives modification instead?

**Comment by jnm** [comment]
Probably not. Your changes to the server's `/etc/hosts` file won't have any effect inside the Docker containers.

**Comment by devisbal** [comment]
But the configuration with the entries on /etc/hosts is working. 
Without any changes in docker-compose.server.yml 


----- Original Message -----

**Comment by jnm** [comment]
That's cool 😎 Have you tried deploying forms or collecting data with Enketo yet?

**Comment by devisbal** [comment]
Yes, The system is working, all 3 access. koboform, kobocat and enketo. 
Form created, deployed and data collected. 

----- Original Message -----

**Comment by jnm** [comment]
Great, thanks for sharing your experience. Is your host OS Linux or something else?

**Comment by devisbal** [comment]
Linux. Ubuntu 16.04.3 LTS 

----- Original Message -----
