### ISSUE TITLE
Error KPI

### ISSUE THREAD

**Issue by bogdhy** [kobotoolbox/kobo-docker#117]
Fresh install on local machine and digitalocean server following the guide, this error everywhere:

`ImproperlyConfigured at /assets/
Could not resolve URL for hyperlinked relationship using view name "user-detail". You may have failed to include the related model in your API, or incorrectly configured the `lookup_field` attribute on this field.

Request Method: GET
Request URL: http://192.168.0.181:8000/assets/?q=asset_type%3Asurvey
Django Version: 1.8.13
Python Executable: /usr/local/bin/uwsgi
Python Version: 2.7.12
Python Path: ['.', '', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-x86_64-linux-gnu', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '/usr/local/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages', '/srv/src/kpi']
Server time: Mon, 12 Jun 2017 07:18:13 +0000
Installed Applications:
('django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'reversion',
 'debug_toolbar',
 'mptt',
 'haystack',
 'kobo.apps.KpiConfig',
 'hub',
 'loginas',
 'webpack_loader',
 'registration',
 'django.contrib.admin',
 'django_extensions',
 'taggit',
 'rest_framework',
 'rest_framework.authtoken',
 'oauth2_provider',
 'markitup',
 'django_digest',
 'raven.contrib.django.raven_compat')
Installed Middleware:
(u'debug_toolbar.middleware.DebugToolbarMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.locale.LocaleMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'hub.middleware.OtherFormBuilderRedirectMiddleware')

Traceback:
File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py" in get_response
  132.                     response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/csrf.py" in wrapped_view
  58.         return view_func(*args, **kwargs)
File "/usr/local/lib/python2.7/dist-packages/rest_framework/viewsets.py" in view
  87.             return self.dispatch(request, *args, **kwargs)
File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py" in dispatch
  466.             response = self.handle_exception(exc)
File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py" in dispatch
  463.             response = handler(request, *args, **kwargs)
File "/usr/local/lib/python2.7/dist-packages/rest_framework/mixins.py" in list
  45.             return self.get_paginated_response(serializer.data)
File "/usr/local/lib/python2.7/dist-packages/rest_framework/serializers.py" in data
  674.         ret = super(ListSerializer, self).data
File "/usr/local/lib/python2.7/dist-packages/rest_framework/serializers.py" in data
  239.                 self._data = self.to_representation(self.instance)
File "/usr/local/lib/python2.7/dist-packages/rest_framework/serializers.py" in to_representation
  614.             self.child.to_representation(item) for item in iterable
File "/usr/local/lib/python2.7/dist-packages/rest_framework/serializers.py" in to_representation
  472.                 ret[field.field_name] = field.to_representation(attribute)
File "/usr/local/lib/python2.7/dist-packages/rest_framework/relations.py" in to_representation
  366.             raise ImproperlyConfigured(msg % self.view_name)

Exception Type: ImproperlyConfigured at /assets/
Exception Value: Could not resolve URL for hyperlinked relationship using view name "user-detail". You may have failed to include the related model in your API, or incorrectly configured the `lookup_field` attribute on this field.
Request information:
GET:
q = u'asset_type:survey'`

What can I do to fix it, there were no errors when the containers came up and not even in the logs after the error showed in the console.

**Comment by esmail** [comment]
@bogdhy, this sounds a [KPI](https://github.com/kobotoolbox/kpi) code issue, possibly caused by recent changes there. I believe we've been able to successfully deploy the latest KPI on our servers, so it might've just been an issue with the [Docker Hub image](https://hub.docker.com/r/kobotoolbox/kpi/builds/) being behind the source repo while the automated image build was waiting to execute.

I'll try it out myself later today. In the meantime, it might be worth doing a `docker-compose pull kpi` and locally testing again.

**Comment by bogdhy** [comment]
@esmail just now I saw that there were 3 new commits with fixes today on KPI repo so I guess I will wait for the new image. Thanks for your answer.

**Comment by esmail** [comment]
The DH automated builds generally don't lag more than a few hours so the latest image is up to date now. I was able to get mine up successfully locally, so give it another try and let us know how it goes.

**Comment by bogdhy** [comment]
I tried it again with a fresh clone from the repo and the latest images and still the same error, maybe I am missing some configuration step, here is how I did it:

1. Clone the repo
2. Created the symlink for docker-compose.local.yml
3. docker-compose pull 
4. Fill the envfile.local.txt
5. Then start with docker-compose up

Should I be doing something different or I am missing something?

**Comment by esmail** [comment]
Interesting. I was working with a `server` setup. Your steps seem fine to me at first glance (I'm assuming you've also carefully gone through the steps in the README); I'll try the `local` setup out and report back.

**Comment by esmail** [comment]
@bogdhy, apologies for the delay. I've just pulled the latest images and tried again with a `local` setup and I couldn't reproduce your issue. Could you please try again and if it doesn't work, share the output of `git diff` (redacting any passwords and secrets)?

**Comment by bogdhy** [comment]
After I removed everything and started with a fresh clone from kobo-docker, I followed the steps from readme. When I ran `docker-compose up` all containers failed. After some digging I found that all lines from most of the files were ending in the carriage return character (^M). I was finally able to fix it using `dos2unix ./**/*` and then recreated the containers and everything went well. I was then able to create a project, add questions, etc. Hope this will help others aswell.

**Comment by esmail** [comment]
Thanks for following up, @bogdhy; I'm sure other users will be able to benefit from your comments. Could you tell us a little about your environment? In particular, are you using Windows?

**Comment by bogdhy** [comment]
OS: elementary OS 0.4.1 loki
Kernel: x86_64 Linux 4.8.0-54-generic

Those file containes CRLF line endings (windows style) instead of simple LF line endings (unix style).

**Comment by esmail** [comment]
Strange; for me in Ubuntu all but a few files use `LF`:
```bash
esmail@esmail-MacBookAir:~/devel/kobo-docker$ for filename in $(find .); do file ${filename}; done | grep -i CRLF
./.vols/static/kpi/xlform/components/angular-ui-utils/ui-utils.js: ASCII text, with very long lines, with CRLF, LF line terminators
./.vols/static/kpi/xlform/components/jquery-migrate/jquery-migrate.js: ASCII text, with CRLF line terminators
./.vols/static/kpi/xlform/components/jquery-migrate/jquery-migrate.min.js: ASCII text, with very long lines, with CRLF line terminators
./.vols/static/kobocat/css/leaflet.ie.css: ASCII text, with CRLF line terminators
./.vols/static/kobocat/css/leaflet.css: ASCII text, with CRLF line terminators
./.vols/static/kobocat/js/Chart.js: ASCII text, with very long lines, with CRLF, LF line terminators
./.vols/static/kobocat/js/jquery.poshytip.js: ASCII text, with very long lines, with CRLF line terminators
./.vols/static/kobocat/bower_components/leaflet-dist/leaflet.ie.css: ASCII text, with CRLF line terminators
./.vols/static/kobocat/bower_components/leaflet-dist/leaflet.css: ASCII text, with CRLF line terminators
./.vols/static/kobocat/bower_components/leaflet-dist/leaflet-src.js: ASCII text, with CRLF, LF line terminators
```

It might be worth trying [`git config --local core.autocrlf true`](https://www.git-scm.com/docs/git-config#git-config-coreautocrlf) so you don't have to keep using `dos2unix` after every checkout.
