### ISSUE TITLE
API calls are returned empty

### ISSUE THREAD

**Issue by tinok** [kobotoolbox/kobo-docker#12]
KC API calls are always returned empty, even when a user is signed in.

https://[servername]/api/v1/forms should return a list of all forms but shows a blank string instead.

The Analyze Data view doesn't work either because no data is returned from the API.

**Comment by esmail** [comment]
The "Analyze" view's API calls (e.g. GET https://kc-local.kobotoolbox.org/api/v1/stats/1) result in 404s.

**Comment by esmail** [comment]
Closed in the linked KC PR(s).

**Comment by esmail** [comment]
Err... now getting seemingly-unsatisfiable authentication requests.
