### ISSUE TITLE
Port remapping to non-default ports

### ISSUE THREAD

**Issue by janknobloch** [kobotoolbox/kobo-docker#121]
Hey all thanks at first for providing a docker container for kobo:

Sadly im facing issues to setup my container properly on a non standard port as im running an apache on the same machine:
Quick setup description:
my apache setup runs on ports 80 / 443 with letsencrypt (kobo independent)

I tried to setup KOBO/Docker the following:

1. Change port mappings in docker-compose.yml to:
```
  ports:
    - 80:8080
    - 443:8090
```
-> this leads to kobo not booting up at all as ngixx tries to grab the non-available 443 port.

2. So I changed the DockerFile in base_images/nginx to:
`EXPOSE 8080 8090`

3. And updated my docker-compose.yml accordingly:
```
  ports:
    - 8080:8080
    - 8090:8090
```
Kobo boots up fine i can access my koboform.domain.tld:8090 url however, the preview (enketo) still directs to 443 as well as I cant deploy my questionnaire giving an 500 internal error.
It looks that some parts of the framework not adapting the port change properly?

How should one adapt the ports correctly ?
Some guidance would be great. Thanks for your help.

Best Jan

**Comment by acutex** [comment]
Hi,

Did you find a solution to the issue?

**Comment by jnm** [comment]
I'm going to close this due to age and us not having the resources to support customized installations like this. That said, if anyone is still having this trouble, I'd check to see whether it's helpful or necessary to change `EXPOSE`. If anyone has a resolution, please submit a PR.
