### ISSUE TITLE
Simple installation instructions for non-programmers

### ISSUE THREAD

**Issue by jnm** [kobotoolbox/kobo-docker#122]
KoBo used to have a Vagrant-based setup that was (arguably) more approachable for users who needed a server for a local, offline network but didn't care to do any development or run a public server.

Perhaps make a new set of instructions for these users with the following in mind:
- [ ] See whether the Docker stack runs properly on ~~Mac~~ (reportedly it does) and Windows; provide instructions for Linux, Mac, and Windows accordingly;
- [ ] Provide instructions without platform-specific steps like `ln -s`;
- [ ] Avoid jargon like `Clone this repository`;
- [ ] Discuss the limitations (security and otherwise) of a local, HTTP-only installation, but don't include parenthetical instructions on HTTPS, Google Analytics, Amazon S3, or any other optional components that don't make sense in an offline setting.

**Comment by baptistae** [comment]
Hi,
I am a new KoboToolbox user with no programming skills. I would be grateful if I can get some simple instruction for installing KoboToolbox on my computer/server. Cheers.

**Comment by jnm** [comment]
@noliveleger, I'm just assigning this to you since you're working on https://github.com/kobotoolbox/kobo-install. If that ends up being sufficiently self-documenting, we can just close this issue. Otherwise, feel free to reassign it to me once `kobo-install` is ready for the public to use.

**Comment by noliveleger** [comment]
@jnm, I'm reassigning it to you because `kobo-install` has to be reviewed before closing this issue. 
Keep in mind. `kobo-install` does not work under `windows`.
