### ISSUE TITLE
Error in access database of the kobotool box on my local machine

### ISSUE THREAD

**Issue by iTechMission** [kobotoolbox/kobo-docker#125]
what to access data base of the kobo toolbox on my local machine. But foolowing error is orruced repeatedly.
Initializing PostGIS.
postgres_1        | Warning: connection to the database failed, disabling startup checks:
postgres_1        | psql: FATAL:  password authentication failed for user "postgres"
postgres_1        | 
postgres_1        | Password: 
postgres_1        | psql: fe_sendauth: no password supplied
postgres_1        | *** /etc/my_init.d/10_init_postgres.bash failed with status 2
postgres_1        | 
postgres_1        | *** Killing all processes...
postgres_1        | *** Running /etc/my_init.d/00_regen_ssh_host_keys.sh...
postgres_1        | *** Running /etc/my_init.d/10_init_postgres.bash...
postgres_1        | Restoring permissions of Postgres cluster data directory.
postgres_1        | 2017-07-04 10:50:52 GMT ERROR:  role "kobo" already exists
postgres_1        | 2017-07-04 10:50:52 GMT STATEMENT:  CREATE USER kobo WITH SUPERUSER;
postgres_1        | 	
postgres_1        | 2017-07-04 10:50:53 GMT ERROR:  database "kobotoolbox" already exists
postgres_1        | 2017-07-04 10:50:53 GMT STATEMENT:  CREATE DATABASE kobotoolbox OWNER kobo
 what would be the error

**Comment by jnm** [comment]
(Closing due to age. Sorry we weren't able to respond earlier. Please reopen if you still have trouble.)

**Comment by fagianijunior** [comment]
Same here: password authentication failed for user "postgres"

in /var/log/syslog
