### ISSUE TITLE
Installed on a non-local server, but no uploading of XLSforms

### ISSUE THREAD

**Issue by ekansa** [kobotoolbox/kobo-docker#126]
I'm getting some weird behavior when I try to upload an XLS form to my docker installed instance of Kobo. I've got it running fine (I guess) on my SSL encrypted Ubuntu 16.10 server (latest updates, upgrades, latest Docker, latest Kobo-docker installation). 

But, when I use my browser to attempt to upload an XLS form (say into my library, or as a project), nothing at all happens after I select the file to upload from my local client machine. There's no error message. There's no javascript error.  When I look at my requests (using the developer's tools), I see no network interaction at all (no POST request or anything). I'm trying with a Windows 10 machine, and have tried with Chrome, Firefox, Microsoft Edge. 

Ideas?

**Comment by jnm** [comment]
(Closing due to age. Sorry we weren't able to respond earlier. Please reopen if you still have trouble.)
