### ISSUE TITLE
Problem in deploying form as survey form on the local server

### ISSUE THREAD

**Issue by acerborealis** [kobotoolbox/kobo-docker#127]
Hi
I am trying to install kobotoolbox on a local machine. I was using the recently updated kobo-docker project from "https://github.com/kobotoolbox/kobo-docker" and followed the steps for local setup successfully. When I opened "http://192.168.75.23:8000/" on browser, it opened successfully and i logged in successfully. I built one form with one question of type string. But when I tried to deploy the form it gave me error "No JSON object could be decoded". What can I do?
Hope I will get solution as early as possible.

Thanks
Regards
Alex

**Comment by janknobloch** [comment]
#162 seems to be the same issue, also #134 should be the same issue.
have you checked your logfiles? esp. the postgre container?
