### ISSUE TITLE
enketo_express container: Unable to find local grunt

### ISSUE THREAD

**Issue by axonxorz** [kobotoolbox/kobo-docker#130]
Using a local checkout of kobotoolbox/enketo-express, with the option configured in `docker-compose.yml`:

    enketo_express:
      build: ../enketo-express/
### Edit
Looks like the issue lies in using a locally checked-out version of enketo-express with:

    enketo_express:
      volumes:
        - ../enketo-express:/srv/src/enketo_express

The following error occurs after a `docker-compose build`, `docker-compose up`

    enketo_express_1  | *** Running /etc/my_init.d/00_regen_ssh_host_keys.sh...
    enketo_express_1  | *** Running /etc/my_init.d/01_enketo_express_copy_config.bash...
    enketo_express_1  | Copying the read-only configuration template into place at `/srv/src/enketo_express/config/config.json`.
    enketo_express_1  | *** Running /etc/my_init.d/01_setup_enketo.bash...
    enketo_express_1  | grunt-cli: The grunt command line interface (v1.2.0)
    enketo_express_1  | 
    enketo_express_1  | Fatal error: Unable to find local grunt.
    enketo_express_1  | 
    enketo_express_1  | If you're seeing this message, grunt hasn't been installed locally to
    enketo_express_1  | your project. For more information about installing and configuring grunt,
    enketo_express_1  | please see the Getting Started guide:
    enketo_express_1  | 
    enketo_express_1  | http://gruntjs.com/getting-started
    enketo_express_1  | *** /etc/my_init.d/01_setup_enketo.bash failed with status 99

**Comment by jnm** [comment]
(Closing due to age. Sorry we weren't able to respond earlier. Please reopen if you still have trouble.)
