### ISSUE TITLE
add google analytics token to Enketo 

### ISSUE THREAD

**Issue by shadimh** [kobotoolbox/kobo-docker#131]
add google analytics token to Enketo config file 
https://github.com/kobotoolbox/enketo-express/tree/master/config#google
the config file is in 
/srv/src/enketo_express/config/config.json

**Comment by jnm** [comment]
I know this is an old issue (that was resolved through other channels), but for anyone else reading, durable changes to the Enketo `config.json` can be made by editing https://github.com/kobotoolbox/kobo-docker/blob/master/enketo_express/config.json in your cloned copy of this repository.
