### ISSUE TITLE
Data functions issues on a standalone server installation

### ISSUE THREAD

**Issue by vladimir-MS** [kobotoolbox/kobo-docker#133]
We are experiencing the recurring issue with the standalone installation of KoBo Toolbox. 

After a period of normal operation (days or weeks), a component in the system stops, and users get different error messages, ranging from "Cannot load data" to HTTP 500, possibly all from the same origin. When the ToolBox is restarted via docker-compose stop/up, normal function restores.

The issue might have been introduced when KoBo Toolbox was upgraded to 158face  Jul 8, 2017. 

Attached please find all the logs from one occurance.
[2017-09-18.zip](https://github.com/kobotoolbox/kobo-docker/files/1313860/2017-09-18.zip)

**Comment by tinok** [comment]
Closing this issue as it was moved to separate repo for treatment.
