### ISSUE TITLE
Database missing table koboform_surveydraft, cannot deploy

### ISSUE THREAD

**Issue by ciscon** [kobotoolbox/kobo-docker#134]
After pulling new images or doing a completely fresh installation, deployment always results in the following error:

postgres_1        | 2017-09-26 15:57:50 GMT ERROR:  relation "koboform_surveydraft" does not exist at character 24
postgres_1        | 2017-09-26 15:57:50 GMT STATEMENT:  SELECT (1) AS "a" FROM "koboform_surveydraft" LIMIT 1

**Comment by jnm** [comment]
Hello! My log for a successfully running instance is filled with those.
```
ubuntu@ubuntu:~/unu$ docker-compose logs postgres | grep surveydraft | head
postgres_1        | 2017-09-20 05:17:03 GMT ERROR:  relation "koboform_surveydraft" does not exist at character 24
postgres_1        | 2017-09-20 05:17:03 GMT STATEMENT:  SELECT (1) AS "a" FROM "koboform_surveydraft" LIMIT 1
postgres_1        | 2017-09-20 05:26:17 GMT ERROR:  relation "koboform_surveydraft" does not exist at character 24
postgres_1        | 2017-09-20 05:26:17 GMT STATEMENT:  SELECT (1) AS "a" FROM "koboform_surveydraft" LIMIT 1
postgres_1        | 2017-09-20 17:25:53 GMT ERROR:  relation "koboform_surveydraft" does not exist at character 24
postgres_1        | 2017-09-20 17:25:53 GMT STATEMENT:  SELECT (1) AS "a" FROM "koboform_surveydraft" LIMIT 1
postgres_1        | 2017-09-20 17:29:07 GMT ERROR:  relation "koboform_surveydraft" does not exist at character 24
postgres_1        | 2017-09-20 17:29:07 GMT STATEMENT:  SELECT (1) AS "a" FROM "koboform_surveydraft" LIMIT 1
postgres_1        | 2017-09-21 09:54:35 GMT ERROR:  relation "koboform_surveydraft" does not exist at character 24
postgres_1        | 2017-09-21 09:54:35 GMT STATEMENT:  SELECT (1) AS "a" FROM "koboform_surveydraft" LIMIT 1
```
This is sloppy and we should correct it, but it should not be stopping you from running the application. What other failure symptoms do you have?

**Comment by ciscon** [comment]
Deployment just always fails with a 500 error on the following post (and that error in the log): http://kobo.localdomainl.com:8000/assets/aTh9eyrCLXDZQmf97S2v7S/deployment/ [active:true]

**Comment by ciscon** [comment]
fyi, the response in that request that results in a 500 error is the following: HTTPConnectionPool(host='app.sitscape.com', port=8001): Max retries exceeded with url: /api/v1/forms (Caused by NewConnectionError(': Failed to establish a new connection: [Errno 111] Connection refused',))
I was guessing the request was crapping out with that db error, but I'm not familiar enough with how any of this works to say for sure.

**Comment by ciscon** [comment]
It would appear that it just won't allow me to use a hostname (one that resolves to the box's ip address) in envfile.local.txt anymore (though until I updated this worked fine).

**Comment by jnm** [comment]
Ah, that's annoying. Thanks for the update, though! Let us know if you find a workaround. One place to look might be `docker-compose.server.yml` (even though I realize you're using `docker-compose.local.yml`): there are three commented-out `extra_hosts` sections that might be helpful for in-container name resolution. You'd have to copy them into `docker-compose.local.yml` and modify to match your situation.

1. https://github.com/kobotoolbox/kobo-docker/blob/babb0c5cff514204de01ca7df6652b2b4de33ac4/docker-compose.server.yml#L84
2. https://github.com/kobotoolbox/kobo-docker/blob/babb0c5cff514204de01ca7df6652b2b4de33ac4/docker-compose.server.yml#L129
3. https://github.com/kobotoolbox/kobo-docker/blob/babb0c5cff514204de01ca7df6652b2b4de33ac4/docker-compose.server.yml#L186

**Comment by ciscon** [comment]
Interesting, I'll give the extra_hosts sections a try later, for now I have a working (but convoluted) solution using haproxy and just configuring the hostname in compose.local.yml with the ip.

**Comment by yeffercardona** [comment]
Buenas tengo un error posterior a ese en el que previno los formularios en kobotoolbox me sale connect ehostunreach y corri kobotoolbox en primer plano y venta este error cual quier ayuda seria de mucho agradecimiento una en el formulario otra en primer plano en el servidor
![2018-05-08](https://user-images.githubusercontent.com/38251649/39824362-c2c3f568-5374-11e8-9c07-7c9f6a2267ab.png)
![Uploading kobo error.png…]()
