### ISSUE TITLE
How to delete a user ?

### ISSUE THREAD

**Issue by fredericmazzini** [kobotoolbox/kobo-docker#144]
Hi,

We would like to use kobo-docker in a production environment? But, for that, we absolutely need to be able to cleanly delete a user and we didn't find a proper way to do it. 
With the admin interface of kobocat and kpi we always have an error :
- kobocat : we have errors like 'update or delete on table "auth_user" violates foreign key constraint ....' on kpi tables,
- kpi : we have error like ''NoneType' object has no attribute '_base_manager' on xform model.

Could you tell us what the best solution is ?

Thanks

Fred

**Comment by devisbal** [comment]
I went to postgres and have to delete each constraint related to the user:
docker exec -it kobodocker_postgres_1 /bin/bash
delete from auth_user where id=3;
DETAIL:  Key (id)=(3) is still referenced from table "authtoken_token".
DETAIL:  Key (id)=(3) is still referenced from table "django_digest_partialdigest".
DETAIL:  Key (id)=(3) is still referenced from table "guardian_userobjectpermission".
DETAIL:  Key (id)=(3) is still referenced from table "hub_extrauserdetail".
DETAIL:  Key (id)=(3) is still referenced from table "main_userprofile".

**Comment by noliveleger** [comment]
You can refer to this thread on community board. 
User deletion should work now.
https://community.kobotoolbox.org/t/cannot-delete-user/1159.
