### ISSUE TITLE
Large Postgres needs more time to stop gracefully

### ISSUE THREAD

**Issue by jnm** [kobotoolbox/kobo-docker#146]
We had to deal with index corruption after `docker-compose restart postgres` on a ~180GB database. I'm not sure if Docker is over-eager to kill processes running inside a container or if there's another issue. Please modify this description as you see fit.

**Comment by noliveleger** [comment]
@jnm is this issue fixed by #276?

**Comment by jnm** [comment]
Sure. The timeouts I use in #278 are arbitrary (and maybe too short for our own huge instances, where I always make a point of sending the appropriate shutdown commands to PostgreSQL and MongoDB **instead of** stopping their containers), but the issue should be resolved for almost all self-hosters.
