### ISSUE TITLE
Periodically clean up KC temporary files

### ISSUE THREAD

**Issue by jnm** [kobotoolbox/kobo-docker#149]
The (inefficient) KC media file export life cycle goes like this:

1. Download every single uploaded media file for the desired survey from S3;
1. ...and stream all of those files into a ZIP, stored in `/tmp`;
1. Upload the resulting ZIP back to S3.

After some tens of minutes, Celery will kill off long-running export jobs. Unfortunately, their incompletely-created or incompletely-uploaded ZIP files are left sitting in `/tmp`, usually taking up lots of disk space (e.g. 25G this evening).

On a non-Docker install, I have an aggressive cron job to remove these temporary files:
```
50 * * * * find /tmp/ -mmin +60 -print -delete
```

**Comment by noliveleger** [comment]
@jnm On docker install, the issue occurs in kobocat container? 
Does celery use a specific format for files? It would be better to delete only files that match a specific pattern.
