### ISSUE TITLE
Inconsistency of data after a restore

### ISSUE THREAD

**Issue by fredericmazzini** [kobotoolbox/kobo-docker#150]
Hi,

If you restore data on a server having a different domain than the one of the server where the backup was made your data are incoherent.  The previous domain is still referenced in the database (_deployment_data  column  of the kpi_asset table) making some kpi functionalities failed (View Gallery, Settings, ...).

Is there any actions to do after the restore ?

Best regards,

Fred,

**Comment by jnm** [comment]
Hi Fred,

Yes, there's a way to fix [this problem](https://github.com/kobotoolbox/kpi/issues/1122). If you access your KPI container (e.g. `docker-compose exec kpi bash`) and run `./manage.py sync_kobocat_xforms`, it should [correct the domain mismatch](https://github.com/kobotoolbox/kpi/blob/242a6def581da4e7830e8a98d47aca35015fa80a/kpi/management/commands/sync_kobocat_xforms.py#L267).

John
