### ISSUE TITLE
Kpi page does not load

### ISSUE THREAD

**Issue by prashantsh** [kobotoolbox/kobo-docker#154]
I just started with a fresh install of ubuntu and running kobo-docker. The installation is successful and after logging in and uploading my form in the form builder. The project list and project detail pages do not load it is just showing the loader. Upon closer inspection from the network tool, The url: <myurl>/assets/?q=asset_type%3Asurvey&limit=200 seems to be throwing 500 internal server error. 

I have tried this with multiple forms and in different machines and it is still showing the same error. The closest other issue I found was https://github.com/kobotoolbox/kobo-docker/issues/117 but the solution mentioned there also didn't work.

Not sure if it is only for me, but I have tried multiple times but still showing the same error. Any help would be highly appreciated.

**Comment by jnm** [comment]
Could you set [`KPI_DJANGO_DEBUG=True`](https://github.com/kobotoolbox/kobo-docker/blob/75814b6a801f12984cd5c2e3719736f63a94fe42/envfiles/kpi.txt#L1) and report the details of the 500 error?

**Comment by prashantsh** [comment]
@jnm thank you for taking the time to respond to my issue. Here is the debug error message. I would also like to point out that this issue arose after adding users to the form to submit the data.

`ImproperlyConfigured at /assets/
Could not resolve URL for hyperlinked relationship using view name "user-detail". You may have failed to include the related model in your API, or incorrectly configured the `lookup_field` attribute on this field.

Request Method: GET
Request URL: https://kf.kobo.nasc.org.np/assets/?q=asset_type%3Asurvey&limit=200
Django Version: 1.8.13
Python Executable: /usr/local/bin/uwsgi
Python Version: 2.7.12
Python Path: ['.', '', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-x86_64-linux-gnu', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '/usr/local/lib/python2.7/dist-packages', '/src/django-digest', '/src/pyxform', '/src/formpack/src', '/usr/lib/python2.7/dist-packages', '/srv/src/kpi']
Server time: Thu, 4 Jan 2018 08:48:03 +0000
Installed Applications:
('django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'reversion',
 'debug_toolbar',
 'mptt',
 'haystack',
 'kobo.apps.KpiConfig',
 'hub',
 'loginas',
 'webpack_loader',
 'registration',
 'django.contrib.admin',
 'django_extensions',
 'taggit',
 'rest_framework',
 'rest_framework.authtoken',
 'oauth2_provider',
 'markitup',
 'django_digest',
 'guardian',
 'raven.contrib.django.raven_compat')
Installed Middleware:
(u'debug_toolbar.middleware.DebugToolbarMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.locale.LocaleMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'hub.middleware.OtherFormBuilderRedirectMiddleware')

Traceback:
File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py" in get_response
  132.                     response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/csrf.py" in wrapped_view
  58.         return view_func(*args, **kwargs)
File "/usr/local/lib/python2.7/dist-packages/rest_framework/viewsets.py" in view
  87.             return self.dispatch(request, *args, **kwargs)
File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py" in dispatch
  466.             response = self.handle_exception(exc)
File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py" in dispatch
  463.             response = handler(request, *args, **kwargs)
File "/usr/local/lib/python2.7/dist-packages/rest_framework/mixins.py" in list
  45.             return self.get_paginated_response(serializer.data)
File "/usr/local/lib/python2.7/dist-packages/rest_framework/serializers.py" in data
  674.         ret = super(ListSerializer, self).data
File "/usr/local/lib/python2.7/dist-packages/rest_framework/serializers.py" in data
  239.                 self._data = self.to_representation(self.instance)
File "/usr/local/lib/python2.7/dist-packages/rest_framework/serializers.py" in to_representation
  614.             self.child.to_representation(item) for item in iterable
File "/usr/local/lib/python2.7/dist-packages/rest_framework/serializers.py" in to_representation
  472.                 ret[field.field_name] = field.to_representation(attribute)
File "/usr/local/lib/python2.7/dist-packages/rest_framework/serializers.py" in to_representation
  614.             self.child.to_representation(item) for item in iterable
File "/usr/local/lib/python2.7/dist-packages/rest_framework/serializers.py" in to_representation
  472.                 ret[field.field_name] = field.to_representation(attribute)
File "/usr/local/lib/python2.7/dist-packages/rest_framework/relations.py" in to_representation
  366.             raise ImproperlyConfigured(msg % self.view_name)

Exception Type: ImproperlyConfigured at /assets/
Exception Value: Could not resolve URL for hyperlinked relationship using view name "user-detail". You may have failed to include the related model in your API, or incorrectly configured the `lookup_field` attribute on this field.
Request information:
GET:
q = u'asset_type:survey'
limit = u'200'

POST: No POST data

FILES: No FILES data

COOKIES:
csrftoken = '1toGB9m7zuTpne3YXWLwvXfPYEsQOWpM'
kobonaut = '40zps2gcsa6lcnj26akky989dtu3co5h'
_ga = 'GA1.3.687735200.1511345936'

META:
wsgi.multiprocess = True
HTTP_REFERER = 'https://kf.kobo.nasc.org.np/'
uwsgi.version = '2.0.13'
SCRIPT_NAME = u''
REQUEST_METHOD = 'GET'
PATH_INFO = u'/assets/'
SERVER_PROTOCOL = 'HTTP/1.1'
QUERY_STRING = 'q=asset_type%3Asurvey&limit=200'
HTTP_X_REAL_IP = '202.166.198.142'
CONTENT_LENGTH = ''
HTTP_USER_AGENT = 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0'
HTTP_CONNECTION = 'keep-alive'
HTTP_COOKIE = '_ga=GA1.3.687735200.1511345936; csrftoken=1toGB9m7zuTpne3YXWLwvXfPYEsQOWpM; kobonaut=40zps2gcsa6lcnj26akky989dtu3co5h'
SERVER_NAME = 'kf.kobo.nasc.org.np'
REMOTE_ADDR = '202.166.198.142'
wsgi.url_scheme = 'https'
SERVER_PORT = '443'
uwsgi.node = 'kpi'
DOCUMENT_ROOT = '/usr/share/nginx/html'
HTTP_X_REQUESTED_WITH = 'XMLHttpRequest'
HTTP_X_FORWARDED_PROTO = 'https'
wsgi.input = <uwsgi._Input object at 0x7fe9da5938e8>
HTTP_HOST = 'kf.kobo.nasc.org.np'
HTTPS = 'on'
wsgi.multithread = False
HTTP_CACHE_CONTROL = 'max-age=0'
REQUEST_URI = '/assets/?q=asset_type%3Asurvey&limit=200'
HTTP_ACCEPT = 'application/json, text/javascript, */*; q=0.01'
wsgi.version = 
HTTP_X_FORWARDED_FOR = '202.166.198.142'
wsgi.errors = <open file 'wsgi_errors', mode 'w' at 0x7fe9daa26e40>
REMOTE_PORT = '57523'
HTTP_ACCEPT_LANGUAGE = 'en-US,en;q=0.5'
wsgi.run_once = False
CONTENT_TYPE = ''
wsgi.file_wrapper = ''
CSRF_COOKIE = u'1toGB9m7zuTpne3YXWLwvXfPYEsQOWpM'
HTTP_ACCEPT_ENCODING = 'gzip, deflate, br'

Settings:
Using settings module kobo.settings
MARKITUP_FILTER = 
MONTH_DAY_FORMAT = 'F j'
SECURE_BROWSER_XSS_FILTER = False
HAYSTACK_SIGNAL_MODELS = 
USE_THOUSAND_SEPARATOR = False
CSRF_COOKIE_SECURE = False
LANGUAGE_CODE = 'en-us'
ROOT_URLCONF = 'kobo.urls'
CELERYD_TASK_TIME_LIMIT = 2100
SKIP_HEAVY_MIGRATIONS = False
BROKER_URL = 'amqp://kpi:kpi@rabbit:5672/kpi'
BASE_DIR = '/srv/src/kpi'
SILENCED_SYSTEM_CHECKS = []
ACCOUNT_ACTIVATION_DAYS = 3
SESSION_SERIALIZER = 'django.contrib.sessions.serializers.JSONSerializer'
STATIC_ROOT = 'staticfiles'
TRACKJS_TOKEN = u'********************'
SYNC_KOBOCAT_XFORMS = True
ALLOWED_HOSTS = ['.kobo.nasc.org.np']
MESSAGE_STORAGE = 'django.contrib.messages.storage.fallback.FallbackStorage'
EMAIL_SUBJECT_PREFIX = '[Django] '
SERVER_EMAIL = 'root@localhost'
SECURE_HSTS_SECONDS = 0
STATICFILES_FINDERS = 
SESSION_CACHE_ALIAS = 'default'
SESSION_COOKIE_DOMAIN = '.kobo.nasc.org.np'
SESSION_COOKIE_NAME = 'kobonaut'
TIME_INPUT_FORMATS = 
SECURE_REDIRECT_EXEMPT = []
DATABASES = {'default': {'ENGINE': 'django.db.backends.postgresql_psycopg2', 'AUTOCOMMIT': True, 'ATOMIC_REQUESTS': False, 'NAME': 'kobotoolbox', 'CONN_MAX_AGE': 0, 'TIME_ZONE': 'UTC', 'PORT': 5432, 'HOST': 'postgres', 'USER': 'kobo', 'TEST': {'COLLATION': None, 'CHARSET': None, 'NAME': None, 'MIRROR': None}, 'PASSWORD': u'********************', 'OPTIONS': {}}}
EMAIL_SSL_KEYFILE = u'********************'
TEMPLATE_DEBUG = False
FILE_UPLOAD_DIRECTORY_PERMISSIONS = None
FILE_UPLOAD_PERMISSIONS = None
MONGO_DB = Database(MongoClient(host=['mongo:27017'], document_class=dict, tz_aware=True, connect=True, j=True), u'formhub')
FILE_UPLOAD_HANDLERS = 
DEFAULT_CONTENT_TYPE = 'text/html'
GIT_REV = {'short': 'fa97306', 'tag': 'unhcr-20170807', 'long': 'fa973062d24f7e68b64cca89412e8b5122ebea94', 'branch': 'master'}
APPEND_SLASH = True
FIRST_DAY_OF_WEEK = 0
DATABASE_ROUTERS = []
DEFAULT_TABLESPACE = ''
YEAR_MONTH_FORMAT = 'F Y'
MONGO_DATABASE = {'HOST': 'mongo', 'PASSWORD': u'********************', 'NAME': 'formhub', 'USER': '', 'PORT': 27017}
CACHES = {'default': {'BACKEND': 'django.core.cache.backends.locmem.LocMemCache'}}
SESSION_COOKIE_PATH = '/'
DEFAULT_DEPLOYMENT_BACKEND = 'kobocat'
SECURE_CONTENT_TYPE_NOSNIFF = False
MIDDLEWARE_CLASSES = 
USE_I18N = True
THOUSAND_SEPARATOR = ','
SECRET_KEY = u'********************'
ENKETO_SURVEY_ENDPOINT = 'api/v2/survey/all'
DEFAULT_INDEX_TABLESPACE = ''
REGISTRATION_EMAIL_HTML = False
LOGGING_CONFIG = 'logging.config.dictConfig'
SIGNING_BACKEND = 'django.core.signing.TimestampSigner'
TEMPLATE_LOADERS = 
WSGI_APPLICATION = 'kobo.wsgi.application'
INTERCOM_APP_ID = None
KOBO_SUPPORT_EMAIL = 'support@yipl.com.np'
X_FRAME_OPTIONS = 'SAMEORIGIN'
CSRF_COOKIE_NAME = 'csrftoken'
HAYSTACK_CONNECTIONS = {'default': {'ENGINE': 'haystack.backends.whoosh_backend.WhooshEngine', 'PATH': '/srv/whoosh/whoosh_index'}}
FORCE_SCRIPT_NAME = None
USE_X_FORWARDED_HOST = False
EMAIL_TIMEOUT = None
SECURE_SSL_HOST = None
DEFAULT_CHARSET = 'utf-8'
SESSION_COOKIE_SECURE = False
CSRF_COOKIE_DOMAIN = '.kobo.nasc.org.np'
FILE_CHARSET = 'utf-8'
DEBUG = True
MONGO_CONNECTION = MongoClient(host=['mongo:27017'], document_class=dict, tz_aware=True, connect=True, j=True)
LANGUAGE_COOKIE_DOMAIN = None
DEFAULT_FILE_STORAGE = 'django.core.files.storage.FileSystemStorage'
INSTALLED_APPS = 
LANGUAGES_BIDI = 
USE_L10N = True
ENKETO_SERVER = 'https://ek.kobo.nasc.org.np/'
STATICFILES_DIRS = 
PREPEND_WWW = False
SECURE_PROXY_SSL_HEADER = 
LANGUAGE_COOKIE_AGE = None
SESSION_COOKIE_HTTPONLY = True
DEBUG_PROPAGATE_EXCEPTIONS = False
INTERNAL_IPS = 
EMAIL_FILE_PATH = '/srv/src/kpi/emails'
SYNC_KOBOCAT_PERMISSIONS = True
GOOGLE_ANALYTICS_TOKEN = u'********************'
LOGIN_URL = '/accounts/login/'
SESSION_EXPIRE_AT_BROWSER_CLOSE = False
CELERYD_TASK_SOFT_TIME_LIMIT = 1800
TIME_FORMAT = 'P'
AUTH_USER_MODEL = 'auth.User'
DATE_INPUT_FORMATS = 
AUTHENTICATION_BACKENDS = 
EMAIL_HOST_PASSWORD = u'********************'
PASSWORD_RESET_TIMEOUT_DAYS = u'********************'
SESSION_FILE_PATH = None
CACHE_MIDDLEWARE_ALIAS = 'default'
SESSION_SAVE_EVERY_REQUEST = False
STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.StaticFilesStorage'
NUMBER_GROUPING = 0
SESSION_ENGINE = 'django.contrib.sessions.backends.db'
CSRF_FAILURE_VIEW = 'django.views.csrf.csrf_failure'
CSRF_COOKIE_PATH = '/'
LOGIN_REDIRECT_URL = '/'
RAVEN_CONFIG = {'dsn': '', 'release': u'fa973062d24f7e68b64cca89412e8b5122ebea94', 'name': 'kf.kobo.nasc.org.np'}
DECIMAL_SEPARATOR = '.'
IGNORABLE_404_URLS = 
LOCALE_PATHS = '/srv/src/kpi/locale'
KOBOCAT_INTERNAL_URL = 'https://kc.kobo.nasc.org.np'
TEMPLATE_STRING_IF_INVALID = ''
ENKETO_VERSION = 'express'
LOGOUT_URL = '/accounts/logout/'
EMAIL_USE_TLS = False
FIXTURE_DIRS = 
EMAIL_HOST = 'localhost'
DATE_FORMAT = 'N j, Y'
DKOBO_PREFIX = False
CAN_LOGIN_AS = <function <lambda> at 0x7fe9ea1b1488>
MEDIA_ROOT = ''
LANGUAGE_COOKIE_PATH = '/'
DEFAULT_EXCEPTION_REPORTER_FILTER = 'django.views.debug.SafeExceptionReporterFilter'
ADMINS = 
SYNC_KOBOCAT_XFORMS_PERIOD_MINUTES = 30
FORMAT_MODULE_PATH = None
DEFAULT_FROM_EMAIL = 'webmaster@localhost'
SECURE_HSTS_INCLUDE_SUBDOMAINS = False
REST_FRAMEWORK = {'DEFAULT_AUTHENTICATION_CLASSES': ['rest_framework.authentication.SessionAuthentication', 'rest_framework.authentication.BasicAuthentication', 'rest_framework.authentication.TokenAuthentication'], 'URL_FIELD_NAME': 'url', 'PAGE_SIZE': 100, 'DEFAULT_PAGINATION_CLASS': 'kpi.serializers.Paginated'}
KOBO_SUPPORT_URL = 'http://help.kobotoolbox.org/'
MEDIA_URL = ''
DATETIME_FORMAT = 'N j, Y, P'
TEMPLATE_DIRS = 
NATIVE_LANGUAGE_NAMES = {u'ku': u'\u0643\u0648\u0631\u062f\u06cc'}
KOBOCAT_URL = 'https://kc.kobo.nasc.org.np'
DISALLOWED_USER_AGENTS = 
ALLOWED_INCLUDE_ROOTS = 
ENKETO_PREVIEW_URI = 'preview'
WHOOSH_PATH = '/srv/whoosh/whoosh_index'
LOGGING = {'loggers': {'sentry.errors': {'level': 'DEBUG', 'propagate': False, 'handlers': ['console']}, 'django.db.backends': {'level': 'ERROR', 'propagate': False, 'handlers': ['console']}, 'raven': {'level': 'DEBUG', 'propagate': False, 'handlers': ['console']}}, 'disable_existing_loggers': False, 'handlers': {'sentry': {'class': 'raven.contrib.django.raven_compat.handlers.SentryHandler', 'level': 'WARNING'}, 'console': {'formatter': 'verbose', 'class': 'logging.StreamHandler', 'level': 'DEBUG'}}, 'formatters': {'verbose': {'format': '%(levelname)s %(asctime)s %(module)s %(process)d %(thread)d %(message)s'}}, 'version': 1, 'root': {'level': 'WARNING', 'handlers': ['sentry']}}
SHORT_DATE_FORMAT = 'm/d/Y'
TEMPLATES = []
EXPOSE_GIT_REV = False
TEST_RUNNER = 'django.test.runner.DiscoverRunner'
CELERYD_MAX_TASKS_PER_CHILD = 7
CACHE_MIDDLEWARE_KEY_PREFIX = u'********************'
SECURE_SSL_REDIRECT = False
TIME_ZONE = 'UTC'
REGISTRATION_AUTO_LOGIN = True
FILE_UPLOAD_MAX_MEMORY_SIZE = 2621440
MANAGERS = 
EMAIL_BACKEND = 'django.core.mail.backends.filebased.EmailBackend'
ANONYMOUS_USER_ID = -1
CELERYD_MAX_CONCURRENCY = 6
LANGUAGE_COOKIE_NAME = 'django_language'
EMAIL_USE_SSL = False
TEMPLATE_CONTEXT_PROCESSORS = 
KPI_PREFIX = '/'
MIGRATION_MODULES = {}
MONGO_CONNECTION_URL = 'mongodb://mongo:27017'
SESSION_COOKIE_AGE = 1209600
SETTINGS_MODULE = 'kobo.settings'
USE_ETAGS = False
LANGUAGES = [('en', u'English')]
HAYSTACK_SIGNAL_PROCESSOR = 'kpi.haystack_utils.SignalProcessor'
FILE_UPLOAD_TEMP_DIR = None
CSRF_COOKIE_AGE = 31449600
STATIC_URL = '/static/'
WEBPACK_LOADER = {'DEFAULT': {'BUNDLE_DIR_NAME': 'jsapp/compiled/', 'POLL_INTERVAL': 0.5, 'TIMEOUT': 5}}
EMAIL_PORT = 25
USE_TZ = True
SHORT_DATETIME_FORMAT = 'm/d/Y P'
TEST_NON_SERIALIZED_APPS = []
ENKETO_API_TOKEN = u'********************'
PASSWORD_HASHERS = u'********************'
ABSOLUTE_URL_OVERRIDES = {}
KOBOCAT_DEFAULT_PERMISSION_CONTENT_TYPES = [('main', 'userprofile'), ('logger', 'xform'), ('api', 'project'), ('api', 'team'), ('api', 'organizationprofile'), ('logger', 'note')]
CELERYBEAT_SCHEDULE = {'sync-kobocat-xforms': {'task': 'kpi.tasks.sync_kobocat_xforms', 'options': {'queue': 'sync_kobocat_xforms_queue', 'expires': 900.0}, 'schedule': datetime.timedelta(0, 1800)}}
UPCOMING_DOWNTIME = False
CACHE_MIDDLEWARE_SECONDS = 600
EMAIL_SSL_CERTFILE = None
ALLOWED_ANONYMOUS_PERMISSIONS = 
CSRF_COOKIE_HTTPONLY = False
DATETIME_INPUT_FORMATS = 
KOBO_SURVEY_PREVIEW_EXPIRATION = 24
EMAIL_HOST_USER = ''

You're seeing this error because you have DEBUG = True in your
Django settings file. Change that to False, and Django will
display a standard page generated by the handler for this status code.`

**Comment by jnm** [comment]
Hi @prashantsh, could you check to see if this scenario applies to you?
https://github.com/kobotoolbox/kobocat/issues/323#issuecomment-355101409

**Comment by prashantsh** [comment]
@jnm Yes that was it :) Thank you for your help, it has helped solve the issue.
