### ISSUE TITLE
unable to verify the first certificate

### ISSUE THREAD

**Issue by HarshadKeluskar** [kobotoolbox/kobo-docker#157]
Hi Team,

We were using SAN certificate for kobotoolbox which got removed and I have configured and installed new wildcard certificate for server. It is installed successfully and I can see this certificate while accessing web URLs. It throwing error in the GUI when I click on preview button in the form (Error: Unable to verify the first certificate). I think I missed something or made one small mistake. Please see below screenshot:
![capture](https://user-images.githubusercontent.com/24381715/34714384-4e0665c2-f54f-11e7-9139-bd1e3c4bdf78.PNG)

Hi all, your help would be highly appreciated.

Please let me know if anyone requires more details.

Thanks,
**Harshad**

**Comment by jnm** [comment]
You may need to include an intermediate certificate in `secrets/ssl.crt`. Try googling `concatenate intermediate certificate` for guidance.

**Comment by stevenvandervalk** [comment]
I also had this error and fixed it by copying the `fullchain.pem` generated by LetsEncrypt client into `ssl.crt` in `kobo-docker/secrets/`.  As per https://community.letsencrypt.org/t/wildcard-certificates-full-chain-and-key-singles-are-cert-chain-and-key/56647
