### ISSUE TITLE
RabbitMQ issue

### ISSUE THREAD

**Issue by ifrecode** [kobotoolbox/kobo-docker#158]
Hi, I'm having some troubles with rabbitmq when I try to launch docker-compose command.
This is the output:

`rabbit_1          | /usr/sbin/rabbitmq-server: 33: /usr/sbin/rabbitmq-server: cannot create /var/log/rabbitmq/startup_log: Permission denied`

I've installed it a couple of weeks ago and everything was running pretty well, after a restart this issue comes out.
I'm new to docker and I don't know where to look for more details/logs. I tried to find out a way to manually edit that directory/file and configurations but I didn't fix it.
It's running on Ubuntu server and I just pulled the latest version (note: it stop to work before the updates).

Any suggestion?
Maybe it's not a lot to work on, if you need more details let me know what and where I can get them!

Thanks!

**Comment by jnm** [comment]
Try this:
```
docker-compose exec rabbit chown -R rabbitmq /var/log/rabbitmq
```
If it works, please close this issue. Thanks!

**Comment by ifrecode** [comment]
Yep, it works! Thanks a lot!
