### ISSUE TITLE
Extended locales for example es-co not giving correct translation-combined.json

### ISSUE THREAD

**Issue by devisbal** [kobotoolbox/kobo-docker#159]
Browser set-up for: es-co
Verified with: https://ee.domain.com/x/manifest.appcache
CACHE MANIFEST
# version: 2018-01-27|07:32|es-co
..
/css/theme-plain.print.css
/locales/en/translation-combined.json
/fonts/fontawesome-webfont.woff?v=4.6.2
..
Do not give:
/locales/es/translation-combined.json

But it works with Browser setup for just: es
CACHE MANIFEST
# version: 2018-01-27|07:56|es
..
/css/theme-plain.print.css
/locales/en/translation-combined.json
/locales/es/translation-combined.json
/fonts/fontawesome-webfont.woff?v=4.6.2

**Comment by jnm** [comment]
Hello @devisbal—if this is an Enketo issue, could you please report it to [https://github.com/kobotoolbox/enketo-express](https://github.com/kobotoolbox/enketo-express)?

If Enketo Express has released a newer version that fixes the bug you observed, please let us know so we can update our Docker configuration.

**Comment by devisbal** [comment]
Hi: 


It's not an enketo issue. 
I have a resent enketo_express installation and do not present this problem, it's only present with the docker. 


On the enketo_express with browser set to es-co it load the /es/ 



CACHE MANIFEST 
# version: 2018-02-01|06:04|es 


CACHE: 
.. 

/css/theme-plain.print.css 
/locales/en/translation-combined.json 
/locales/es/translation-combined.json 
/fonts/fontawesome-webfont.woff?v=4.6.2 
.. 

----- Original Message -----

**Comment by jnm** [comment]
I think this is working now, but please reopen this issue if you still have trouble.
![image](https://user-images.githubusercontent.com/2085013/46447235-a8e8b680-c74e-11e8-95de-4908fe6b4b59.png)
