### ISSUE TITLE
Nginx container missing  kobo.conf

### ISSUE THREAD

**Issue by s4parke** [kobotoolbox/kobo-docker#16]
We're running into an issue with the nginx container -- it can't find a file called kobo.conf.  

Dockerfile:13

```
ln -s /etc/nginx/kobo.conf /etc/nginx/sites-enabled/kobo && \
rm -rf /etc/nginx/kobo.conf
```

The kobo.conf file is being deleted, however it does not appear to exist in the first place. 
Any suggestions are appreciated, thanks!

**Comment by dorey** [comment]
I'm [seeing the lines you're referencing at this part of base_images/nginx/Dockerfile](https://github.com/kobotoolbox/kobo-docker/blob/master/base_images/nginx/Dockerfile#L13-L14).

**Comment by esmail** [comment]
Closed. Thanks for the report, @s4parke!

**Comment by s4parke** [comment]
Thanks very much @esmail!
