### ISSUE TITLE
KoBo on Raspberry Pi [error] standard_init_linux.go:178: exec user process caused "exec format error"

### ISSUE THREAD

**Issue by mponsserrano** [kobotoolbox/kobo-docker#164]
Hi,
I'm trying to install KoBoToolbox on Raspberry Pi 3. I have followed the guide and finally, when I open the browser with the 192.168.x.x:8000 I get the resolve: The connection with the server can not be established. 

I run the sudo docker-compose logs -f command and I obtain the following error: standard_init_linux.go:178: exec user process caused "exec format error".

I have read that Raspberries uses ARM and not x86_64 processors.

Anyone has already tried this? Has anyone the solution?

Thanks a lot

**Comment by noliveleger** [comment]
We are willing to support `RaspberryPi`.  You can retry with latest version of docker and `https://github.com/kobotoolbox/kobo-install`.
Unfortunately, we have our hands full as the core team and cannot provide much support for such requests. 

You can visit https://community.kobotoolbox.org/ for help.
