### ISSUE TITLE
New Accounts Lockdown

### ISSUE THREAD

**Issue by devisbal** [kobotoolbox/kobo-docker#166]
How can we have the "create an account" locked?

I have read that setting:
REGISTRATION_OPEN = False
in /srv/src/kpi/kobo/settings.py
This is accomplished.
https://github.com/jpstaub/kobo-docker-ripcord/wiki/New-Accounts-Lockdown

Can this be an external variable that is setup when the dockers at bring up?

**Comment by jnm** [comment]
You can set this in the Django admin interface now: https://github.com/kobotoolbox/kpi/issues/1735
