### ISSUE TITLE
HTTP 500 on delete user

### ISSUE THREAD

**Issue by vladimir-MS** [kobotoolbox/kobo-docker#167]
We are facing an issue on a stadalone installation of KoBo Toolbox. The system was initially installed less than a year ago from kobo-docker repo, and updated 2-3 times since. It is uncertain when the condition set in, but initially it was not present i.e. everything was working fine.

The issue: delete user action in Django admin returns HTTP 500, for any user:

> AttributeError at /admin/auth/user/83/delete/
> `NoneType' object has no attribute '_base_manager'`

I am attaching the entire debug message from attempted delete user action: [AttributeError at _admin_auth_user_83_delete_.pdf](https://github.com/kobotoolbox/kobo-docker/files/1819267/AttributeError.at._admin_auth_user_83_delete_.pdf)

Creating users functions, both through /admin/ and /accounts/register.although there is a HTTP 500 on one of AJAX calls in the registration process, a call to path /me/ that returns HTTP 500.

Any help is greatly appreciated.

**Comment by noliveleger** [comment]
Ticket is closed due to inactivity.

Take a look at this thread on community forum.
https://community.kobotoolbox.org/t/cannot-delete-user/1159.
`HTTP Error` on registration process often means that SMTP server is not set correctly.
