### ISSUE TITLE
Anyone has cloned a proper working project of this?

### ISSUE THREAD

**Issue by DanishFayaz** [kobotoolbox/kobo-docker#169]
I've tried several times to deploy this app. But usually something breaks, either its this or that. Does anyone has ever deployed one completely and used it? If has, can you please share their version? It'll be nice to have that as most people are having issues on this. Thanks

**Comment by janknobloch** [comment]
yes I have using this fix: #162 
deploy with issue222 deploy a single form, upgrade to newest version.

**Comment by jnm** [comment]
Closing in favor of #162, which I plan to resolve today. Thanks for your help, @janknobloch
