### ISSUE TITLE
Make KPI media accessible (via NGINX?)

### ISSUE THREAD

**Issue by jnm** [kobotoolbox/kobo-docker#175]
`PrivateFileField`s work fine, but URLs for regular `FileField`s (e.g. https://github.com/kobotoolbox/kpi/issues/1738) produce 404s when using local storage.

**Comment by lucernae** [comment]
Hi @jnm, precisely what I encountered.
So, was the decision to let nginx handle regular media url or put urlpattern for `^media/` in Django?

**Comment by jnm** [comment]
I don't think we came to a solution on this. The people who wanted custom logos etc. were using Amazon S3 storage.

**Comment by GrupoCATO** [comment]
¿Existe alguna manera de ver los archivos multimedia de manera local?. Tambien intento cambiar el logo opr defecto desde el modelo "Hub.ConfigurationFile" pero no me deja acceder a las imagenes cargadas desde alli, me arroja un error 404 no encontrado

**Comment by GrupoCATO** [comment]
> Hi @jnm, precisely what I encountered.
> So, was the decision to let nginx handle regular media url or put urlpattern for `^media/` in Django?

Realmente este comentario me sirvio, agrege la ruta para la carpeta "media" en el archivo urls.py y me ha funcionado de maravilla!

`url(r'^media/(?P<path>.*)$','django.views.static.serve',{'document_root':settings.MEDIA_ROOT}),`

Ahora ya me cargan las imagenes y logos que cargo desde el modelo "Hub.ConfigurationFile".

Saludos!

**Comment by noliveleger** [comment]
@jnm should we close this issue since https://github.com/kobotoolbox/kobo-docker/pull/217/files has been released?

**Comment by jnm** [comment]
@noliveleger, probably, but does that work with `ConfigurationFile`s? I don't think I've tested them.

@GrupoCATO, cuidese con `django.views.static.serve`, porque https://docs.djangoproject.com/en/1.8/howto/static-files/ dice que
> This method is grossly inefficient and probably insecure, so it is unsuitable for production.

Creemos que ahora hay una solución que no necesita modificaciones manuales, pero tenemos que probarla con `ConfigurationFile`.

**Comment by noliveleger** [comment]
@jnm, I haven't tested it either.

**Comment by d7volker** [comment]
I have the same problem.
And https://github.com/kobotoolbox/kobo-docker/pull/217/files this doesn't help, because in my eyes it is the wrong directory. I don't know, perhaps this was created for any other purpose? Uploaded content via the admin interface resides here: .vols/kpi_media/

I am interested in this feature with local storage. Do you accept a pull request?

**Comment by d7volker** [comment]
I made it to work for us:

```
# diff -u kobo-docker/docker-compose.frontend.yml.orig kobo-docker/docker-compose.frontend.yml
--- kobo-docker/docker-compose.frontend.yml.orig        2020-10-03 19:08:37.203295125 +0200
+++ kobo-docker/docker-compose.frontend.yml     2020-10-03 19:11:44.028675196 +0200
@@ -100,6 +100,7 @@
         - ./.vols/kobocat_media_uploads:/media
         - ./nginx/docker-entrypoint.d/30-init-kobo-nginx.sh:/docker-entrypoint.d/30-init-kobo-nginx.sh
         - ./nginx/kobo-docker-scripts/:/kobo-docker-scripts
+        - ./.vols/kpi_media:/srv/kpi_media
     restart: always
     networks:
       kobo-fe-network:
```

```
# diff -u kobo-docker/nginx/kobo-docker-scripts/templates/nginx_site_default.conf.tmpl.orig kobo-docker/nginx/kobo-docker-scripts/templates/nginx_site_default.conf.tmpl
--- kobo-docker/nginx/kobo-docker-scripts/templates/nginx_site_default.conf.tmpl.orig   2020-10-03 19:02:03.896395552 +0200
+++ kobo-docker/nginx/kobo-docker-scripts/templates/nginx_site_default.conf.tmpl        2020-10-03 19:05:43.738015082 +0200
@@ -105,6 +105,11 @@
 
     error_page 418 = /static/html/Offline.html;
 
+    # kpi_media files
+    location /media {
+        alias /srv/kpi_media/;
+    }
+
     location / {
         # Proxy through uWSGI.
         ${kpi_include_uwsgi_pass}
```

**Comment by noliveleger** [comment]
@d7volker, this solution seems to expose all private media files too (e.g. exports). IMHO, It would be better to make a change the configuration module to upload files somewhere else and expose this folder.
