### ISSUE TITLE
Enketo Express Version

### ISSUE THREAD

**Issue by devisbal** [kobotoolbox/kobo-docker#176]
Why master is still using:

enketo_express:
  image: kobotoolbox/enketo-express-extra-widgets:1.55.6

and branch ocha-aws
  enketo_express:
    image: kobotoolbox/enketo-express-extra-widgets:1.65.1-jnm

Can the docker-compose.server.yml be changed to use other recommended version of enketo-express?

**Comment by jnm** [comment]
Indeed! We'll include an update to 1.65.5 when closing out https://github.com/kobotoolbox/kobo-docker/issues/170
