### ISSUE TITLE
Problems XLSForms referencing external .CSV files

### ISSUE THREAD

**Issue by ekansa** [kobotoolbox/kobo-docker#183]
Hi all,

I've just deployed kobo-docker (absolute latest build on an Ubuntu 16.04 server) and everything appears to be working properly. However, I'm having trouble with forms that reference external CSV files. None of the following features of XLSforms have worked for me:

- pulldata
- select_one_from_file
- select_one_external

My XLSforms validate well with (https://opendatakit.org/xlsform/). When I attempt to deploy a form with "select_one_from_file" I get an error in that reads "Unknown question type 'select_one_from_file...". Pulldata and "select_one_external" forms do not through errors, but then they don't work with enketo_express in my instance of Kobotoolbox. The external files just aren't used in the web browser form.

I need to reference external data in my forms to populate pick-lists that will need to change. I'm at a complete loss on how to understand what's wrong. It would be great if this repo could include some XLSforms to use in testing (especially testing of more complex features like access of CSV files from a form), so I can eliminate the possibility that I just have badly designed forms and Kobotoolbox is working fine.

Any help will be much appreciated!
  
**UPDATE**
I looked into this a bit more. When I have a valid XLSform with an "external_choices" sheet, and I can upload it into Kobotoolbox, but when I attempt to deploy, I get an HTTP 500 error to this address: https://my-kobo-deployment.org/assets/{identifier}/deployment/

**Comment by ronna** [comment]
Hi @ekansa 

Is it possible to share your forms so that I can test from this end. if just the small part that is not working if the forms have some confidential data

**Comment by ekansa** [comment]
OK! None of the following. 

Note: Github won't let me upload a "trenches.csv" file, but it's exactly the same as the external_sheet data in debug-external-sheet.xlsx file.


[debug-search.xlsx](https://github.com/kobotoolbox/kobo-docker/files/2102677/debug-search.xlsx)
[debug-external-sheet.xlsx](https://github.com/kobotoolbox/kobo-docker/files/2102678/debug-external-sheet.xlsx)
[debug-from-file.xlsx](https://github.com/kobotoolbox/kobo-docker/files/2102679/debug-from-file.xlsx)


THANKS for your help!!

**Comment by ekansa** [comment]
Anyone have any suggestions? Please?

**Comment by ekansa** [comment]
Just a gentle poke to see if some advice may be available...

**Comment by ekansa** [comment]
Sorry to bug! I know everyone is busy, I'm just at a loss as to where I can get some help on this issue.

**Comment by jnm** [comment]
I know this is an old issue and that we had a little bit of discussion over at https://groups.google.com/forum/#!topic/kobo-developers/q6bc4bMWZEQ, but I wanted to let you know that there is progress being made:
https://github.com/kobotoolbox/kpi/issues/2000
https://github.com/kobotoolbox/kobocat/issues/480
https://github.com/kobotoolbox/formpack/issues/177

**Comment by prashantsh** [comment]
Has this feature been incorporated?

**Comment by jnm** [comment]
Yes, we now use upstream Pyxform and can benefit from all its wonderful features, including `select_one_from_file` and `select_multiple_from_file`. For documentation, see https://github.com/XLSForm/pyxform/issues/30#issue-59308643. There's an open issue to have proper documentation for this on XLSForm.org: https://github.com/XLSForm/xlsform.github.io/issues/164
