### ISSUE TITLE
ERROR: You cannot remove a running container d536b4b733595159d6694eca6ebcba07cfb1ca6a1b746514e7b0e63b59f42847. Stop the container before attempting removal or use -f

### ISSUE THREAD

**Issue by panditji** [kobotoolbox/kobo-docker#184]
hi Martijn van de Rijdt,
Greeting for the day
 thanks in Advance :)
how you doing.
i'm facing problem while i'm using" docker-compose up"
**"ERROR: You cannot remove a running container d536b4b733595159d6694eca6ebcba07cfb1ca6a1b746514e7b0e63b59f42847. Stop the container before attempting removal or use -f"**

im following 2 documents : for installation kobo-docker on my local
1.https://github.com/kobotoolbox/kobo-docker
2.http://www.bayramkotan.com/how-to-install-kobotoolbox-by-using-docker-on-ubuntu-server-16-04/

even i used 
docker-compose stop/down  but same error. "**ERROR: You cannot remove a running container d536b4b733595159d6694eca6ebcba07cfb1ca6a1b746514e7b0e63b59f42847. Stop the container before attempting removal or use -f**"

but whenever trying to run docker-compose up : im facing again and agin same error.

**Comment by janknobloch** [comment]
check and remove all containers and images from docker
`docker ps -a` shows all containers also non running ones
`docker rm CONTAINERID -f` removes container
`docker images` shows all images 
`docker rmi IMAGEID -f` removes the image

after removing all images and containers try to run docker-compose up again.
