### ISSUE TITLE
User with access to all projects in server

### ISSUE THREAD

**Issue by anahi-src** [kobotoolbox/kobo-docker#185]
Hello, I would like to know if it is possible to setup a superuser with access to all projects within a local server by default; that is, whenever a user X creates a project, it will be automatically available to the superuser without having user X sharing such project.

**Comment by jnm** [comment]
Sorry, there is not. This is not, unfortunately, what you're asking for, but [KPI](https://github.com/kobotoolbox/kpi/blob/41e264ddb4e0eafca3b973f59dc823afa7d339ad/dependencies/pip/requirements.txt#L33) does include the [django-loginas](https://pypi.org/project/django-loginas/) plugin.
