### ISSUE TITLE
Not Working on OS-X

### ISSUE THREAD

**Issue by aozisik** [kobotoolbox/kobo-docker#19]
Using the latest version of docker-compose and docker toolset (1.10, I guess), it is not possible to run this project. Here are some of the problems I have encountered, how I tried to address them and have failed so far:

- All containers were running, however mongo container complained about a db.lock file already existing or being inaccessible. Inside the .vols directory, there was no such file. Even after running chmod 777 on .vols folder, the mongo container was not able to write.

- Quick google search indicated this might be an issue with boot2docker. I tried with dinghy instead. This time the same problem occurred with postgres container.

- Then I changed the path for the .vols directory and pointed it to my /tmp directory. This seemed to have solved the permission issue (although it's not a good situation, as files will not be persisted) This time I got "South" driver not supported error. A quick search again and I figured this has to do with upgrading Django. 

- Cloned the up-to-date repos from github and build kpi and kobocat machines using the docker files inside these repos instead of the images. Still no luck. Same error.

- Looked up the commit log for the kobocat repo, turns out there has been a change regarding this "South" package. (I am not very familiar with Django or Pip). I tried to rollback to the latest released tag and decided to build all my images from those points. That did not work either.

- I switched back to the latest commits and decided to manually remove South package via pip

This seemed to work but now I am getting 400 Bad request when I visit the domain I have set up from local env file. The furthest I got was seeing a login form but some css files were missing.

So it is all messed up on OS X (El Capitan, btw). This looks like an awesome project but right now impossible to work with due to this issue. Pretty sure there is some solution or something that I am totally missing here. I would love some help!

**Comment by esmail** [comment]
Hi, @aozisik. Thanks for trying this out on OS X; it sounds like you got farther using dinghy than we've gotten with Docker Compose in our limited OS X testing. Sorry for the difficulties with getting things running, this repository's not quite stable yet. The good news is that we've made some changes that I think should get you up and running, so please do a `docker-compose pull` and let us know how it goes!

**Comment by esmail** [comment]
Working under Docker OS X beta with [these instructions](https://github.com/kobotoolbox/kobo-docker/commit/c9539544e34f28fb7d06d3f7449e6332ce74ab0a#diff-853770876f27981131bcc85cc8d5790cR27).
