### ISSUE TITLE
Can't download form to mobile app nor use it online

### ISSUE THREAD

**Issue by anahi-src** [kobotoolbox/kobo-docker#191]
Hi there, I am running Kobo-docker on a personal server. After deploying a project, I can see it listed on the mobile app but I can't download it (get 404 error). I also tried opening my forms online and I get this message from enketo:

Request to https://kobocat.e2mc-kobo.org/Anahi/formList?formID=aGtpg4HPLpDfaHGk9ViUvr failed.

note that I have ran the "docker-compose exec kobocat chown -R wsgi /srv/src/kobocat" as in #162 but it doesn't do anything

**Comment by anahi-src** [comment]
Funny thing, no issues with forms created by the superuser

**Comment by anahi-src** [comment]
actually, I noticed that it works fine with some users

**Comment by anahi-src** [comment]
ok, after further testing, it would seem that it fails with forms created by users whose usernames have uppercase characters

**Comment by jnm** [comment]
That's good to know and this issue report will be a good reference for other people who encounter the same problem.

We disallow uppercase usernames already in the registration form; please take care to observe the validation criteria there if you create users by some other means:
https://github.com/kobotoolbox/kpi/blob/f62a0c58a0b4c90c6e5a96182feb86a54a74dcfb/kpi/forms.py#L9-L15
