### ISSUE TITLE
Enketo Editing images do not show. It's looking at wrong url

### ISSUE THREAD

**Issue by devisbal** [kobotoolbox/kobo-docker#193]
When editing a form on the browser, the images are been requested to kc.kobotoolbox.org instead of kc.mydomain.com

https://ek.mydomain.com/media/get/https/kc.kobotoolbox.org/media/admin/attachments/2e43343cc40c4bedb0ac5a77e2643aac/171ee61c-84be-4e04-ae68-a812360903a0/1521398027181-medium.jpg

Also I think is related, when looking for max-size I got error 401
GET /submission/max-size/::YYpq HTTP/1.1" 401 72

Note:
    "instanceAttachments": {
        "1521398084020.jpg": "/media/get/https/kc.kobotoolbox.org/media/admin/attachments/2e43343cc40c4bedb0ac5a77e2643aac/171ee61c-84be-4e04-ae68-a812360903a0/1521398084020-medium.jpg",
        "1521398027181.jpg": "/media/get/https/kc.kobotoolbox.org/media/admin/attachments/2e43343cc40c4bedb0ac5a77e2643aac/171ee61c-84be-4e04-ae68-a812360903a0/1521398027181-medium.jpg"
    }

**Comment by devisbal** [comment]
I did find the problem.
The definition for KOBOCAT_URL is missing in the file:
scripts/runtime_variables_kobocat.source.bash
I just added:
export KOBOCAT_URL="https://${KOBOCAT_PUBLIC_SUBDOMAIN}.${PUBLIC_DOMAIN_NAME}"
And it's working now.

This is because:  kobocat/onadata/settings/common.py
Have:
KOBOCAT_URL = os.environ.get('KOBOCAT_URL', 'https://kc.kobotoolbox.org')
So an external definition is required

I think that also it's required also for the case of not public domain:
export KOBOCAT_URL="http://${HOST_ADDRESS}:${KOBOCAT_PUBLIC_PORT}"

**Comment by jnm** [comment]
I'd be happy to merge a pull request with these changes :)

**Comment by devisbal** [comment]
Pull request have been done

**Comment by noliveleger** [comment]
Fix has been applied
