### ISSUE TITLE
Is there a test plan for a kobo-docker installation?

### ISSUE THREAD

**Issue by marjetika** [kobotoolbox/kobo-docker#195]
I installed kobo-docker on my server, and I need to test it to make sure everything works correctly.
I started working on a test plan today. But I don't want to re-invent the wheel, if anyone has already done that.

**Comment by jnm** [comment]
For some very basic checking, you could visit `http://your-domain/service_health`. That will verify that [KPI](https://github.com/kobotoolbox/kpi/), [KoBoCAT](https://github.com/kobotoolbox/kobocat/), and [Enketo Express](https://github.com/kobotoolbox/enketo-express/) are responsive, and it will make sure that Postgres and Mongo are running.

A very rough list of things to test (pulled from an in-progress Selenium suite) consists of:

* Login with an existing account
* Delete all forms
* Create a new form from scratch, add a sample question
* Preview the form
* Save and close the form
* Export form to XLS
* Import XLS form
* Deploy the imported form - existing
* Open the form in Enketo, enter and submit data
* Export data to XLS
* Delete the project
* Verify no forms
* Log out
* In a form with a GPS question, check that map loads
* Once form has data, load reports
* Create a custom report with only the first and last question
* Once form has data, load table and then an individual submission
* Share form with another user via the list view (/#/forms)
* Share form with another user via form landing (/#/forms/[UID]/landing)
* Clone a project
* Try to access a publicly shared project (from another account)
* Search for block by choosing collection
* Search for block by entering tag
* Create a new question block from scratch
* Subscribe to Library Collection (previously 'Import a Library Collection')
* Create a new collection
* Move a question block into the new collection
* Modify a question block's tags
* delete all blocks from the library
* delete collection from library
* share collection with other user
* Archive a project
* Change project name and description
* Share a deployed form, that has collected data, with another user via summary (/#/forms/[UID]/summary)
* Remove a user from the sharing permissions
