### ISSUE TITLE
Redis connect ECONNREFUSED 127.0.0.1:6379 Error 

### ISSUE THREAD

**Issue by sumantmann** [kobotoolbox/kobo-docker#199]
<img width="951" alt="screen shot 2018-08-21 at 8 51 51 pm" src="https://user-images.githubusercontent.com/10502724/44411576-74e17980-a584-11e8-96ca-14e15fd2f1c6.png">
Redis error coming while installing kobo-docker on mac using docker for mac.
I am not able to find a fix for this.
Thanks

**Comment by jnm** [comment]
You cannot set your `HOST_ADDRESS` to `127.0.0.1`. Even if you're running locally, you must use the address of your network interface (perhaps `en0` or `en1`, depending on your setup). Do not use a loopback address or hostname (like `localhost`).

If you are already using a valid `HOST_ADDRESS`, try removing all containers with `docker-compose rm -fv`, and then bring them up again with `docker-compose up -d`.

**Comment by noliveleger** [comment]
Ticket closed due to inactivity. 
Please visit https://community.kobotoolbox.org/c/kobo-install for help.
