### ISSUE TITLE
kobocat  502 bad gateway

### ISSUE THREAD

**Issue by Eliie58** [kobotoolbox/kobo-docker#200]
I am trying to install kobo toolbox on a local server, i followed the instructions, and almost got everything working.
I am able to login, and create forms, but when trying to deploy the forms, i get the following error:
`your form cannot be deployed because it contains errors:

No JSON object could be decoded
`

After further investigation, if i go to http://my.domain:8000/service_health i get the following:

```
FAIL

Mongo: OK in 0.0646 seconds
Postgres: OK in 0.00295 seconds
Enketo [http://my.domain:8005/]: OK in 1.92 seconds
KoBoCAT [http://my.domain:8001]: HTTPError(u'502 Server Error: Bad Gateway for url: http://my.domain:8001/service_health/',) in 12.0 seconds
```

And if i run `docker ps` i get the following:
![image](https://user-images.githubusercontent.com/27285272/45266576-8f14c600-b465-11e8-9c3a-ea52bd8edbf6.png)

In my envfile.local.txt i have 

> KOBOCAT_PUBLIC_PORT=8001

Any help would be appreciated.

**Comment by jnm** [comment]
Can you load http://my.domain:8001 successfully? Note that if you're not logged in, you'll be redirected to http://my.domain:8000.

**Comment by noliveleger** [comment]
Ticket closed due to inactivity. 
Please have a look at https://github.com/kobotoolbox/kobo-install or visit https://community.kobotoolbox.org/c/kobo-install for help.
