### ISSUE TITLE
No space left on device

### ISSUE THREAD

**Issue by Kobocash** [kobotoolbox/kobo-docker#201]
kobo-bash: cannot create temp file for here-document: No space left on device

Its likely from tmp files, how can i delete tmp files ?

**Comment by jnm** [comment]
Try removing all your containers (`docker-compose rm -fv`). Your data will remain intact, but all temporary files inside the containers should be flushed. Then use `docker-compose up -d` to recreate and start your containers.

Beyond this, we unfortunately don't have the resources to help with administering your particular system. If you find a bug that's causing the creation of an excessive amount of temporary files, please open another issue.
