### ISSUE TITLE
Form Preview Crashes with https

### ISSUE THREAD

**Issue by chlarsen** [kobotoolbox/kobo-docker#202]
Dear All,
I have installed Kobo ToolBox Docker image as local application, and want to serve it to the Internet behind me separate Nginx reverse proxy (that is not part of the Docker image).
Installation went well, and I can access the entire Kobo Toolbox without any issues via http.
With https, I have a weird issue: The form preview crashes just before the "pumping circle" image appears that indicates the loading form preview. There is no error message in the Nginx logs, nor anything visible in the docker logs, nor anything on the web application.
My (separate) reverse proxy Nginx header settings are here, and apply to both the http and https modes.
Any ideas, what I might be missing?
Thank you!
Chris

**Comment by jnm** [comment]
Is this different than #203?
