### ISSUE TITLE
Form Preview Loads Endlessly When Running via HTTP

### ISSUE THREAD

**Issue by chlarsen** [kobotoolbox/kobo-docker#203]
As the form preview failed to ever load properly, when running the local installation behind an Nginx-powered https reverse proxy, things started to look better, when using http, only. (Which is of course not safe - but consider this for debugging purposes, only.) However, the preview gets stuck at the "pumping circle" stage. What is woring, or what have I missed?
I deliberately do not want to install the server version, because I need to control other (non-Docker) web applications via a reverse proxy that sits in front of them all, including the docker'd Kobo toolbox.
Any ideas? Thank you!
Chris

**Comment by jnm** [comment]
This may have no bearing on your problem, but note that Enketo takes a longer time to start compared to the other services. Have a look at `docker-compose logs -f` and post any interesting information you find there.

Unfortunately, we have our hands full as the core team and cannot provide much support for individual installations. Someone else in the community may be able to help, however.

**Comment by noliveleger** [comment]
Ticket closed due to inactivity. 
Please visit https://community.kobotoolbox.org/c/kobo-install for help.
