### ISSUE TITLE
How to add users?  User registration failing

### ISSUE THREAD

**Issue by chuxau** [kobotoolbox/kobo-docker#207]
Hi, 

* I have deployed fine, and can login with details setup before launching docker-compose.  However, it's not clear to me how to other users.

* So, I tried to register addional accounts, but clicking submit on the registration form (https://forms.example.org/accounts/register/#/) fails to a 502 status message (Bag Gateway) .. 

* I am tailing the logs (for all containers) while trying to register and the logs display nothing at all .. 

* If I switch on Chrome's developer tools, I see the following two error as possible causes .. 
```
no kpi-root-url meta tag set. defaulting to ""
.... <snipped>
no kpi-root-url meta tag set. skipping react-router init
.... <snipped>
login confirmed anonymous user is not logged in
```

* So, it seems like I am missing a simple configuration in my setup .. Please can someone help point me in the right direction.

* Searching witin the sources, I see this variable referenced within Javascript files .. within one of the docker volumes ..  But it's probably better not to change the sources, and I don't know what the correct URL ought to be anyways .. 

* Also, it would be great to be able to add users usingCLI at the back-end .. Is it possible to manage users that way ?

Thanks in adavnce.

**Comment by noliveleger** [comment]
It often happens when the SMTP is not set correctly.
Unfortunately, we have our hands full as the core team and cannot provide much support for individual installations.  Someone else in the community may be able to help, however.
Please visit https://community.kobotoolbox.org/ for help.
