### ISSUE TITLE
Internal Server Error when viewing /forms

### ISSUE THREAD

**Issue by stevenvandervalk** [kobotoolbox/kobo-docker#213]
Hi!  Thank you so much for the project. It is perfectly designed for our use case of collecting information remotely.  We're doing pest management research for CSIRO Australia and would love to use your managed cluster, but will definitely go over the 5gb of media per month and not sure we qualify as humanitarian.  

So, we've deployed kobo-docker at https://feraltrax.org.  However, frequently during testing - but not all the time... - I run into the error below (possibly because I didn't bother with SMTP credentials and am validating users via django admin?)

```
Failed to load resource: the server responded with a status of 500 (INTERNAL SERVER ERROR)
app-c0792240bc1a1747e4c7.js:1 
login not verified 500 INTERNAL SERVER ERROR
```
at

`https://koboform.feraltrax.org/#/forms`

Can you advise a way to debug this or possible workarounds?  

Thank you in advance!

**Comment by jd-alexander** [comment]
did you end up fixing this?

**Comment by jd-alexander** [comment]
Hey @stevenvandervalk I just fixed my issue. It was related to the firewall in my ubuntu config so I am good now 👍

**Comment by shashankmc** [comment]
@jd-alexander I'm currently facing this issue with a docker deployment and it's being very consistent now. Can you share the changes you did with respect to the firewall config? Might give that a shot and see if it fixes this issue!
