### ISSUE TITLE
Feature request : active directory

### ISSUE THREAD

**Issue by Stopi** [kobotoolbox/kobo-docker#221]
Hi there,
thanks for all your good work.
How about Active Directory integration in near future ?

It should be possible to add a new configuration file for people who already have a users database (which any company or institute have) and don't expect them to create a new one, asking for users to enter a new password, etc...

If you consider this, it may not be that difficult, according to this post : https://partofthething.com/thoughts/authenticating-and-populating-users-in-django-using-a-windows-active-directory-and-sasl/

At least an LDAP integration would be welcome.

**Comment by jnm** [comment]
Thanks for the kind words :) Someone else posed a similar question: https://github.com/kobotoolbox/kobo-docker/issues/210. In addition to your helpful link, there are a lot of packages to extend the built-in Django authentication system that we use: https://djangopackages.org/grids/g/authentication/. It should be possible (in theory!) to use these with KoBoToolbox, but unfortunately integrating with external authentication systems is not a priority for the core team at this time.

I would suggest bringing up your feature request on the community forum, https://community.kobotoolbox.org/c/feature-wishlist. It's a good place for us to work together to find funding for enhancements like this.
