### ISSUE TITLE
Performance issue with cascading select

### ISSUE THREAD

**Issue by Stopi** [kobotoolbox/kobo-docker#224]
Hi,
I followed this article :
http://support.kobotoolbox.org/creating-forms/general/adding-cascading-select-questions

And for 500 entries, it works great.
However, I have a database of 8000 villages, spreaded inside 128 districts from 17 provinces.
This doesn't work, because of performance issues.

I could copy/paste the data (according to format used in https://docs.google.com/spreadsheets/d/1C_uDOkjjbv5Kx3lyOY7ORwM-muW6BKVzdaPMB1X8-2A/edit#gid=0).
Then, after a while (few minutes, have to be patient), the question is generated.
I can save and then even export it in XML.

However, the processing of this question is so long that I can't edit it, nor even previsualize the final form. It just load forever (probably stuck because of a timeout).

Is there a way to improve this ?
To me 8000 items is something javascript should handle easily...

Then if it hangs like that on my browser, I can't imagine having it running on a cheap tablet.

**Comment by jnm** [comment]
http://xlsform.org/en/#external-selects
For further assistance: https://community.kobotoolbox.org/
