### ISSUE TITLE
Error 500 on registration

### ISSUE THREAD

**Issue by szabozoltan69** [kobotoolbox/kobo-docker#225]
When I pushed the "Create Account" button on the first user registration (in the freshly installed KoBoToolbox, Workstation version), I received an error 500. Maybe some (email) port is not open?

**Comment by noliveleger** [comment]
@szabozoltan69 I think you fixed this. Do you mind to write down a note about what to do to fix this in case other users encounter the same issue?
When it's done. Please close the issue. 
Thank you.

**Comment by szabozoltan69** [comment]
The issue is solved by given a working email address (instead of the one that the installer offered by default).
