### ISSUE TITLE
Data > Table View not working

### ISSUE THREAD

**Issue by sm2x** [kobotoolbox/kobo-docker#229]
Clone the latest kobo-docker, everything works OK except:
-  Clicking on Data/Table gives blank screen, so I checked the logs on Dev Console and got this **"TypeError: Cannot read property 'filter' of undefined"**

**Comment by noliveleger** [comment]
No related to `kobo-docker` but seems to be related to `kpi`or `kobocat`.
Please visit https://community.kobotoolbox.org/ for information and help.
