### ISSUE TITLE
Document user registration

### ISSUE THREAD

**Issue by esmail** [kobotoolbox/kobo-docker#23]

**Comment by noliveleger** [comment]
@jnm, @mdestaubin, @tinok? Is there such documentation on https://community.kobotoolbox.org/?

**Comment by jnm** [comment]
I don't know what this means. Maybe initial user registration if email isn't set up? https://github.com/kobotoolbox/kobo-install/ adds a superuser during the install process; maybe that's all we need?

**Comment by noliveleger** [comment]
I guess
