### ISSUE TITLE
Use redis as Celery broker

### ISSUE THREAD

**Issue by jeverling** [kobotoolbox/kobo-docker#24]
Redis is running anyway (in fact two containers) so I think it makes sense to get rid of the RabbitMQ container and instead use one of the Redis instances.
It is possible to specify different databases when connecting, but even without that it shouldn't be a problem to use one of the Redis instances as Celery broker.
What do you think?

**Comment by esmail** [comment]
Not a priority for us at the moment, but if you'd like to fork and make a PR, we'd love some community involvement.

**Comment by jeverling** [comment]
That's great to hear, I will create a PR in the next days. I agree it's not
high priority at all.

**Comment by noliveleger** [comment]
`kobo-docker` now uses Redis as a Celery broker.
