### ISSUE TITLE
Security issue reported by DigitalOcean (Mongo)

### ISSUE THREAD

**Issue by jonathanf** [kobotoolbox/kobo-docker#250]
Hi, 
As a scope to the previous issue #249 (Redis), now forward a security issue report for your consideration now about Mongo:

> Hi there,
> 
> We?ve received a notification from 3rd party security researchers, the Shadowserver Foundation, that your Droplet at xxxx.xxx.xxx.xxx is running a MongoDB instance configured in a way that may be insecure.
> 
> This configuration may allow attackers to potentially access your MongoDB instance and remove or modify data hosted within it. This note is not to inform you that there has been a data compromise, but rather that your data might be at risk.
> 
> For securing your MongoDB instance on Ubuntu, refer to this tutorial: https://www.digitalocean.com/community/tutorials/how-to-install-and-secure-mongodb-on-ubuntu-16-04
> 
> For securing your MongoDB instance on CentOS, refer to this tutorial: https://www.digitalocean.com/community/tutorials/how-to-install-mongodb-on-centos-7
> 
> Additionally we have a tutorial covering basics of MongoDB security that's not specifically related to either Ubuntu or CentOS specific information at: https://www.digitalocean.com/community/tutorials/how-to-securely-configure-a-production-mongodb-server
> 
> We also offer Cloud Firewalls – available in all regions at no additional cost – to protect your Droplet from traffic attempting to access it without permission. Learn more about Cloud Firewalls here: https://do.co/intro-to-cloud-firewalls
> 
> The security of all systems in our network is extremely important to us and we strongly encourage you to review your configuration promptly.
> 
> Regards, Security Operations Center DigitalOcean

**Comment by jnm** [comment]
Rolling into #249
