### ISSUE TITLE
Docker-Compose files

### ISSUE THREAD

**Issue by luisbauti92** [kobotoolbox/kobo-docker#251]
Hi, I have a question about the documentation.

I want to set up my own server kobotoolbox, but the documentation is not understood on how to start the docker-compose.

for example:

```
2) Edit composer file docker-compose.yml

Depending of which version you installed, it should be a symlink to docker-compose.local.yml or docker-compose.server.yml.
```
![Screenshot_2019-09-17 kobotoolbox kobo-docker](https://user-images.githubusercontent.com/20865922/65061631-59dc6700-d948-11e9-8f22-327e81d4ca4a.png)

Which of these docker-compose files should I use?

None have the name indicated in the documentation

Any suggestions on how to set up my own kobotoolbox server with docker?

**Comment by noliveleger** [comment]
@luisbauti92, You should give [kobo-install](https://github.com/kobotoolbox/kobo-install) a try.
It will create config files for you and start your own `kobotoolbox` env.

To start frontend containers: 
`docker-compose -f docker-compose.frontend.yml -f docker-compose.frontend.override.yml up -d`

To start backend containers: 
`docker-compose -f docker-compose.backend.master.yml -f docker-compose.backend.master.override.yml up -d`

To start postgres replica: 
`docker-compose -f docker-compose.backend.slave.yml -f docker-compose.backend.slave.override.yml up -d`

where `*.override.yml` files contain custom parameters specific to your own server.

**Comment by luisbauti92** [comment]
@noliveleger, Hi I have this:

`Where do you want to install?
[/home/labautistab/Descargas/kobo-docker]: 
Please confirm path [/home/labautistab/Descargas/kobo-docker]
	1) Yes
	2) No
[1]:  
Do you want to see advanced options?
	1) Yes
	2) No
[1]: 
What kind of installation do you need?
	1) On your workstation
	2) On a server
[2]: 
Please choose which network interface you want to use?
	eno1) 172.22.240.233
	other) Other
	enp0s20f0u5) 192.168.42.222
[eno1]: 
Do you want to use separate servers for frontend and backend?
	1) Yes
	2) No
[1]: 
Which role do you want to assign to this server?
	1) frontend
	2) backend
[frontend]: 
Do you use DNS for private routes?
	1) Yes
	2) No
[2]: 
IP address (IPv4) of backend server?
[172.22.240.233]: 
Public domain name [kobo.local]: 
KPI sub domain [kf]: 
KoBoCat sub domain [kc]: 
Enketo Express sub domain name [ee]: 
Do you want to use HTTPS?
	1) Yes
	2) No
[2]: 
Is `KoBoToolbox` behind a reverse-proxy/load-balancer?
	1) Yes
	2) No
[2]: 
SMTP server: 
SMTP port [25]: 
SMTP user: 
From email address [support@kobo.local]: 
Super user's username [administrator]: 
Super user's password [fassil00]: 
Docker Compose prefix? (leave empty for default): 
Staging mode?
	1) Yes
	2) No
[2]: 
Postgres database [kobotoolbox]: 
Postgres user [kobo]: 
Postgres password [bJTZWizrslcBi~rc]: 
Do you want to customize service ports?
	1) Yes
	2) No
[2]: 
Do you want to use AWS S3 storage?
	1) Yes
	2) No
[2]: 
Google Analytics Identifier: 
Google API Key: 
Do you want to use Sentry?
	1) Yes
	2) No
[2]: 
Do you want to tweak uWSGI settings?
	1) Yes
	2) No
[2]: 
Do you want to activate backups?
	1) Yes
	2) No
[2]: 
`

and so:

![Sin título](https://user-images.githubusercontent.com/20865922/65717820-32844900-e070-11e9-9fd5-ec6b7a107bf4.jpg)

but, when try connect with another device in my local network (LAN) I haven't response for example:
http://172.22.240.233    => http://kf.kobo.local/ 

but when into to http://kf.kobo.local (in my local server) it's work

Any idea how to connect from another device to my LAN server?

Thanks.

**Comment by noliveleger** [comment]
First of all, you should not expose your credentials on GH. 

`kf.kobo.local` is for local purposes. 

You need to add domains to your DNS server. Let's say your public domain is `mydomain.com`

Add 3 A records:
- `kf.mydomain.com`
- `kc.mydomain.com`
- `ee.mydomain.com`

**Comment by luisbauti92** [comment]
> 
> 
> First of all, you should not expose your credentials on GH.
> 
> `kf.kobo.local` is for local purposes.
> 
> You need to add domains to your DNS server. Let's say your public domain is `mydomain.com`
> 
> Add 3 A records:
> 
>     * `kf.mydomain.com`
> 
>     * `kc.mydomain.com`
> 
>     * `ee.mydomain.com`

I have a question, is necessary a DNS server? because i want connect a smartphone with kobotoolbox in a local server (http://172.22.240.233)

it could be this way:

http://kf.172.22.240.233
http://kc.172.22.240.233
http://ee.172.22.240.233

Thanks a lot

**Comment by noliveleger** [comment]
Yes a (local) DNS server is necessary if you want your server to be accessible from your other computers. Otherwise you can add an entry for each domain in `hosts` file of each computer.
And no, you can't not mix ips and domain names. 

Due to the small nature of our team and large volume of users, we cannot provide support or guidance for all github issues requests. 
Please visit https://community.kobotoolbox.org/c/kobo-install for help.
