### ISSUE TITLE
Add cron task for KPI and KoBoCAT cleanup jobs

### ISSUE THREAD

**Issue by jnm** [kobotoolbox/kobo-docker#253]
> Yep, I would run delete_revisions, delete_import_task, delete_asset_snapshot every night too (at least every week) with --vacuum.  Now, it's gonna be very long to catch up.  As --vacuum doesn't lock the DB.

https://www.flowdock.com/app/kobotoolbox/servers/threads/oKEKcVKslqu_T3RFrvrlJ9DB-G7

**Comment by noliveleger** [comment]
I changed my mind about using ubuntu cron. It's more user-friendly to add them `celery` periodic tasks which can be controlled from the Django admin interface.
