### ISSUE TITLE
enketo express image does not support PDF generation.

### ISSUE THREAD

**Issue by kryptt** [kobotoolbox/kobo-docker#260]
The docker image as it is currently shipped fails to generate valid PDF files. 

1st issue is it is missing x11 and chromium related system libraries;
running apt install chromium-chromedriver inside the instance helped. 

after the workaround for the first issue, it fails with 

```json
{
    "message": "PDF generation failed: Failed to launch chrome!\n[1127/144000.634343:ERROR:zygote_host_impl_linux.cc(89)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.\n\n\nTROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md\n",
    "code": "500"
}
``` 

since the docker image never downgrades from the root user which would be good practice anyway.. I placed this in this project but let me know if it is the wrong place to do so.

Thanks!

**Comment by jnm** [comment]
ok, thank you. i'm not enthusiastic about adding x11 and chromium to the image, but we do want to support pdf generation eventually.
