### ISSUE TITLE
Restore from backup created 

### ISSUE THREAD

**Issue by NoMadS803** [kobotoolbox/kobo-docker#263]
I created a backup manually to MongoDB, PostgreSQL, Redis like this 

> docker exec -it kobodocker_kobocat_1 /srv/src/kobocat/docker/backup_media.bash
> docker exec -it kobodocker_mongo_1 /bin/bash /kobo-docker-scripts/backup-to-disk.bash
> docker exec -it -e PGUSER=kobo kobodocker_postgres_1 /bin/bash /kobo-docker-scripts/backup-to-disk.bash
> docker exec -it kobodocker_redis_main_1 /bin/bash /kobo-docker-scripts/backup-to-disk.bash

and i want to restore it but i can`t.

I tried this 

> MongoDB: mongorestore --archive=<path/to/mongo.backup.gz> --gzip
> PostgreSQL: pg_restore -U kobo -d kobotoolbox -c "<path/to/postgres.pg_dump>"
> Redis: gunzip <path/to/redis.rdb.gz> && mv <path/to/extracted_redis.rdb> /data/enketo-main.rdb

but not working for me 
any help ?!

**Comment by jnm** [comment]
Please post your question to https://community.kobotoolbox.org/c/kobo-install/ and include details about why it's not working (error messages, data doesn't appear in the application, etc.).
