### ISSUE TITLE
Please Share Complete Process How To Configure Kobo On Linux (Local Machine)

### ISSUE THREAD

**Issue by email2shahfaisal** [kobotoolbox/kobo-docker#269]
**Description**
 

**Steps to Reproduce**

**Expected behavior**

**Desktop**

 - OS:  
 - Python Version: 
 - Docker Version: 
 - Docker Compose Version:
 
**Additional context**

**Comment by email2shahfaisal** [comment]
Please Share Complete Process How To Configure Kobo On Linux (Local Machine)

**Comment by noliveleger** [comment]
Hi @email2shahfaisal, 
As you may have read when posting your issue: 

> NOTE: IF YOU HAVE ANY PROBLEMS DURING THE INSTALLATION PLEASE VISIT OUR COMMUNITY FORUM AND POST YOUR DETAILED QUESTION THERE:  https://community.kobotoolbox.org/c/kobo-install. Due to the small size of our team and large volume of users, we cannot provide support or guidance via GitHub issues. Please only create an issue for reporting an actual bug in the installation script 

You can also at [kobo-install repository](https://github.com/kobotoolbox/kobo-install).
