### ISSUE TITLE
running docker-compose up

### ISSUE THREAD

**Issue by allankaranja** [kobotoolbox/kobo-docker#27]
hi
am receiving the following log message when i try running docker-compose up command..
 *** Killing all processes...
kobocat_1         | *** Running /etc/my_init.d/00_regen_ssh_host_keys.sh...
kobocat_1         | *** Running /etc/my_init.d/01_wait_for_rabbit.bash...
kobocat_1         | Waiting for container `rabbit`.
kobocat_1         | 2016/05/16 08:06:47 Waiting for host: tcp://172.17.0.2:5672
kobocat_1         | 2016/05/16 08:07:27 Timeout after 40s waiting on dependencies to become available: [tcp://172.17.0.2:5672]
kobocat_1         | *** /etc/my_init.d/01_wait_for_rabbit.bash failed with status 1
kobocat_1         | 
kobocat_1         | *** Killing all processes...
kobocat_1         | *** Running /etc/my_init.d/00_regen_ssh_host_keys.sh...
kobocat_1         | *** Running /etc/my_init.d/01_wait_for_rabbit.bash...
kobocat_1         | Waiting for container `rabbit`.
kobocat_1         | 2016/05/16 08:07:27 Waiting for host: tcp://172.17.0.2:5672
kobocat_1         | 2016/05/16 08:08:07 Timeout after 40s waiting on dependencies to become available: [tcp://172.17.0.2:5672]
kobocat_1         | *** /etc/my_init.d/01_wait_for_rabbit.bash failed with status 1
kobocat_1         | 
kobocat_1         | *** Killing all processes...
kobocat_1         | *** Running /etc/my_init.d/00_regen_ssh_host_keys.sh...
kobocat_1         | *** Running /etc/my_init.d/01_wait_for_rabbit.bash...
kobocat_1         | Waiting for container `rabbit`.
kobocat_1         | 2016/05/16 08:08:08 Waiting for host: tcp://172.17.0.2:5672
kobocat_1         | 2016/05/16 08:08:48 Timeout after 40s waiting on dependencies to become available: [tcp://172.17.0.2:5672]
kobocat_1         | *** /etc/my_init.d/01_wait_for_rabbit.bash failed with status 1
kobocat_1         | 
kobocat_1         | *** Killing all processes...
kobocat_1         | *** Running /etc/my_init.d/00_regen_ssh_host_keys.sh...
kobocat_1         | *** Running /etc/my_init.d/01_wait_for_rabbit.bash...
kobocat_1         | Waiting for container `rabbit`.
kobocat_1         | 2016/05/16 08:08:49 Waiting for host: tcp://172.17.0.2:5672

this is part of the log as it is very long...
kindly assist

**Comment by esmail** [comment]
@allankaranja, I've made a change that might have fixed this issue. Could you give it another try? If it still doesn't work, I'd be interested to see the RabbitMQ log files in `./log/rabbitmq/` and the output of `docker-compose logs rabbit`.

**Comment by allankaranja** [comment]
thanks a lot @esmail 
I have been able to work past that error..thank you for the feedback am now at the logging stage..I have tried to create an account in that logging page but i havent received any confirmation link in my inbox..so I was asking whether there is a standard username and password to get started with?.
again thank you

**Comment by esmail** [comment]
Great. Did you happen to do anything in particular to get past it, or did it just go away when you ran it again?

Regarding logging in, you'll use the `KOBO_SUPERUSER_USERNAME` and `KOBO_SUPERUSER_PASSWORD` you set in step 6 of the setup procedure.

**Comment by allankaranja** [comment]
I removed the rabbit image then pull again and the problem was all fixed...I am able to loging now and am testing it..
Thanks

**Comment by esmail** [comment]
Great :)

If you have any other support requests, you can contact us at support.kobotoobox.org or raise code issues here.
