### ISSUE TITLE
Redis connection failed.

### ISSUE THREAD

**Issue by vishal-ghawale** [kobotoolbox/kobo-docker#271]
Hi,

We have installed kobotoolbox on ubuntu and facing below error when running docker-compose up.

{ Error: Redis connection to redis-main.domain.name:6379 failed -                                                                                    getaddrinfo ENOTFOUND redis-main.domain.name redis-main.domain.name:6379
enketo_express_1  | 19:32:27 0|enketo  |     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26)
enketo_express_1  | 19:32:27 0|enketo  |   errno: 'ENOTFOUND',
enketo_express_1  | 19:32:27 0|enketo  |   code: 'ENOTFOUND',
enketo_express_1  | 19:32:27 0|enketo  |   syscall: 'getaddrinfo',
enketo_express_1  | 19:32:27 0|enketo  |   hostname: 'redis-main.domain.name',
enketo_express_1  | 19:32:27 0|enketo  |   host: 'redis-main.domain.name',
enketo_express_1  | 19:32:27 0|enketo  |   port: 6379 }
enketo_express_1  | 19:32:27 0|enketo  | Worker 5058 sadly passed away. It will be reincarnated.

Thanks in advance
Vishal

**Comment by naxaamulya** [comment]
Is redis container up and running??

**Comment by noliveleger** [comment]
Hello @vishal-ghawale, if you've read the disclaimer when creating issues, we are a small team, we cannot provide support or guidance via GitHub issues. Please only create an issue for reporting an actual bug.
Please visit https://community.kobotoolbox.org/c/kobo-install for help and support. 

Having that said:  It seems you haven't changed your configuration files and updated the templates. You are still using the placeholders. Please try to install with [kobo-install](https://github.com/kobotoolbox/kobo-install). It handles the configuration files creation for you.
