### ISSUE TITLE
email settings

### ISSUE THREAD

**Issue by ivanvuk36** [kobotoolbox/kobo-docker#32]
What would be the proper way to set parameters for local  smtp server?
You have all parameters in smtp.txt file but
I noticed that dkobo settings.py has hardcoded most of the settings

EMAIL_HOST = 'smtp.gmail.com' 
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER') 
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD') 
EMAIL_PORT = 587 
EMAIL_USE_TLS = True
 
Also where we can set DEFAULT_FROM_EMAIL parameter?
(it is used in settings.py )

if os.environ.get('DEFAULT_FROM_EMAIL'): 
  DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL') 
  SERVER_EMAIL = DEFAULT_FROM_EMAIL

**Comment by esmail** [comment]
@ivanvuk36, the `DEFAULT_FROM_EMAIL` setting will finally be integrated into [`smtp.txt`](https://github.com/kobotoolbox/kobo-docker/blob/09a552c/envfiles/smtp.txt#L13) once #21 is merged.

Regarding your other question, `dkobo` isn't actually in use here, only the newer [`kpi`](https://github.com/kobotoolbox/kpi), which imports the email settings from the environment [here](https://github.com/kobotoolbox/kpi/blob/8eb4ef9/kobo_playground/settings.py#L317-L332).
