### ISSUE TITLE
KoBoCAT received this request on port 8000, when 8001 should have been used.

### ISSUE THREAD

**Issue by MakElblotto** [kobotoolbox/kobo-docker#332]
Sorry in advance - not sure if this is a kobo-docker issue, or a kobo-install issue. 
The issue is also presents only intermittently on boot.

**Description**
Visiting the login page for KoboToolbox displays a `System configuration error` The error is as follows:

```
Please contact the administrator of this server.
If you are the administrator of this server: KoBoCAT received this request on port 8000, when 8001 should have been used. Please see https://github.com/kobotoolbox/kobo-docker/issues/301 for more information.
Thanks for using KoBoToolbox.
```
This specific issue is marked as closed/resolved in kobo-docker in August 2020 however, and I didn't see any specific steps I could take to resolve the issue on my end. 

**Steps to Reproduce**
Install KoboToolbox using `Kobo-Install` on a Ubuntu 20.04 virtual machine, in local Workstation mode. Https is not enabled. No other defaults (other than passwords) have been changed.
Confirm that `kf.kobo.local`, `ee.kobo.local` operate as expected (forms can be uploaded, submitted, etc).
Shut down (virtual) server
Cold-boot (virtual) server
Wait for all KoboToolbox Docker container services to be up and running
Attempt to visit the main KoboToolbox login page `http://kf.kobo.local`

**Expected behavior**
Visiting the URL `http://kf.kobo.local` should display the log-in page, instead of an error message.

 - OS:  `Ubuntu 20.04.3 LTS`
 - Python Version:  `3.8.10`
 - Docker Version: `20.10.12, build e91ed57`
 - Docker Compose Version: `1.29.2, build 5becea4c`
 
**Additional context**
This issue appears (to my untrained eye) to be a race-condition of some sort on start-up, as it doesn't always occur.

**Additional notes about the server's config**
The server (virtual machine) has two NICs defined in `/etc/netplan/` . The first NIC is disabled (used during the install, disabled/removed from the virtual machine after installation), the second NIC has a static IP addresses assigned. 
Docker post-install instructions have been followed (as per recommendation in this issue: https://github.com/kobotoolbox/kobo-install/issues/148 )
The server's firewall has been disabled.
VirtualBox guest additions has been installed on the server.

**Comment by noliveleger** [comment]
Hello @MakElblotto, 

Are you facing this after a fresh install or after an upgrade?

**Comment by MakElblotto** [comment]
Hi @noliveleger, 
This occurs after a fresh install. 

Could be entirely coincidental, but we have noticed that occurrences of this - though difficult to quantify due to the intermittent nature - seemed to have reduced in frequency after #331 is/was merged in.

**Comment by noliveleger** [comment]
I found a pattern that make me reproduce this issue on regular basis. This happens when KoBoCAT and KPI containers restart and their IP addresses are swapped. 
It can occur at startup or on a manual restart. 

To reproduce the problem: 
- Start the environment 
- Look at the KPI and KoBoCAT ip addresses 
- Restart KPI and KoBoCAT in the opposite order of their ip addresses. Example: if KPI has `172.27.0.5` and KoBoCAT has `172.27.0.2`, run `./run.py -cf restart kpi kobocat` 
- Validate that KPI gets `172.27.0.2` and `KoBoCAT gets `172.27.0.5`
- Try to access KPI login should return the error described by @MakElblotto above.
