### ISSUE TITLE
Check new database path while upgrading kobo-docker

### ISSUE THREAD

**Issue by ValterGomesSerafim** [kobotoolbox/kobo-docker#343]
**Description**

I am trying to upgrade an old version of kobo-docker to 2.022.44b version. 
Thank you very much for providing the upgrading-related documentation.
I have passed all steps in [Upgrading from an old version of kobo-docker(before November 17, 2022)](https://github.com/kobotoolbox/kobo-docker/blob/master/doc/November-2022-Upgrade.md)
After my experience, I think the following positions should be fixed.

- Step 16
  When I run the following command to start the server, it doesn't work.
  ```
  root@postgres:/# su - postgres -c '/usr/lib/postgresql/14/bin/pg_ctl -D /var/lib/postgresql/data/ start'
  ```
I think the directory path should be fixed to `/var/lib/postgresql/data14/` in the above command, because we set the `new-datadir` to `/var/lib/postgresql/data14/`.
It's also not same with the new database location mentioned in Step 2 .
In Step 2, we set it as   `- ./.vols/db14:/var/lib/postgresql/data14`

Could you please check the directory path part in step 15, 16, 17 of PostgreSQL of the indications?
Thank you.

**Comment by noliveleger** [comment]
Hello @ValterGomesSerafim ,

I think the paths are correct. I followed this documentation for 5-6 upgrades and I copied/pasted the commands exactly the way they are in the doc, and it worked all the time. 

> I think the directory path should be fixed to /var/lib/postgresql/data14/ in the above command, because we set the new-datadir to /var/lib/postgresql/data14/.

Actually in step 14, you have to exit the one-off container, **change the path** in the YAML file (first thing to do in step 15). 
If you follow those steps, new upgraded PostgreSQL 14 data should be located in `/var/lib/postgresql/data/`, not in `/var/lib/postgresql/data14/` (even if the folder on the host is still `./.vols/db14`).

**Comment by ValterGomesSerafim** [comment]
Thank you for your reply.

yes, you're right.
It was my mistake. It works.
