### ISSUE TITLE
Getting error while doing docker installation

### ISSUE THREAD

**Issue by ajinkyagadewar** [kobotoolbox/kobo-docker#36]
kobocat_1         | `kpi` uWSGI service ready.
kobocat_1         | *** Running /etc/my_init.d/10_init_kobocat.bash...
kobocat_1         | KoBoCAT intializing...
kobocat_1         | Synchronizing database.
kobocat_1         | Your environment is:"onadata.settings.kc_environ"
kobocat_1         | Traceback (most recent call last):
kobocat_1         |   File "manage.py", line 21, in <module>
kobocat_1         |     execute_from_command_line(sys.argv)
kobocat_1         |   File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
kobocat_1         |     utility.execute()
kobocat_1         |   File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 328, in execute
kobocat_1         |     django.setup()
kobocat_1         |   File "/usr/local/lib/python2.7/dist-packages/django/__init__.py", line 18, in setup
kobocat_1         |     apps.populate(settings.INSTALLED_APPS)
kobocat_1         |   File "/usr/local/lib/python2.7/dist-packages/django/apps/registry.py", line 108, in populate
kobocat_1         |     app_config.import_models(all_models)
kobocat_1         |   File "/usr/local/lib/python2.7/dist-packages/django/apps/config.py", line 198, in import_models
kobocat_1         |     self.models_module = import_module(models_module_name)
kobocat_1         |   File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
kobocat_1         |     __import__(name)
kobocat_1         |   File "/srv/src/kobocat/onadata/apps/viewer/models/__init__.py", line 1, in <module>
kobocat_1         |     from onadata.apps.viewer.models.parsed_instance import ParsedInstance  # flake8: noqa
kobocat_1         |   File "/srv/src/kobocat/onadata/apps/viewer/models/parsed_instance.py", line 84, in <module>
kobocat_1         |     @task
kobocat_1         |   File "/usr/local/lib/python2.7/dist-packages/celery/task/__init__.py", line 38, in __call__
kobocat_1         |     return self.task(*args, **kwargs)
kobocat_1         |   File "/usr/local/lib/python2.7/dist-packages/celery/five.py", line 307, in __getattr__
kobocat_1         |     module = __import__(self._object_origins[name], None, None, [name])
kobocat_1         |   File "/usr/local/lib/python2.7/dist-packages/celery/task/base.py", line 17, in <module>
kobocat_1         |     from celery.app.task import Context, TaskType, Task as BaseTask  # noqa
kobocat_1         |   File "/usr/local/lib/python2.7/dist-packages/celery/app/__init__.py", line 22, in <module>
kobocat_1         |     from .base import Celery, AppPickler
kobocat_1         |   File "/usr/local/lib/python2.7/dist-packages/celery/app/base.py", line 19, in <module>
kobocat_1         |     from amqp import promise
kobocat_1         | ImportError: cannot import name promise
kobocat_1         | *** /etc/my_init.d/10_init_kobocat.bash failed with status 1

**Comment by azri** [comment]
This issue is solved after when if  kobocat:issue_222 image is used in the docker-compose.yml file. But KPI still not running. It is showing Bad Request (400) message.

**Comment by ajinkyagadewar** [comment]
Any update?

**Comment by esmail** [comment]
Resolved by kobotoolbox/kobocat#231.

**Comment by azri** [comment]
Installed with latest code. This error is not raising, and containers were up and running. But the KPI and Kobocat urls http://localhost:8000 and http://localhost:8001 are showing **Bad Request (400)**
