### ISSUE TITLE
Rabbitmq refuses logins for kobocat and kpi

### ISSUE THREAD

**Issue by vladimir-spintech** [kobotoolbox/kobo-docker#38]
I am trying to run the local version of kobo-docker, but it doesn't work. I didn't modify anything except for  envfile.local.txt

In the main log I can see the errors like this:
> kobocat_1         | [2016-06-08 12:24:02,441: ERROR/MainProcess] consumer: Cannot connect to amqp://kobocat:**@rabbit:5672/kobocat: Couldn't log in: a socket error occurred.

And in rabbit@rabbit.log:
> PLAIN login refused: user 'kobocat' - invalid credentials

Same with kpi

**Comment by esmail** [comment]
Probably need to do a `git pull` and then a `docker-compose pull`.

**Comment by esmail** [comment]
Not reproducible.
