### ISSUE TITLE
Bad Request (400)

### ISSUE THREAD

**Issue by azri** [kobotoolbox/kobo-docker#39]
We are trying to install Kobotoolbox on the local machine. Followed all the steps as per README. Once docker containers are up and running did not see any errors in logs but the URLs http://localhost:8000 and http://localhost:8001 are showing **Bad Request (400)**  message. Enketo URL http://localhost:8005 showing the message "Enketo Express for KoBo Toolbox is running! " and displayed the list of supported languages.

Unable to identify the issue? envfile.local.txt file contents are

```
HOST_ADDRESS=
ENKETO_API_TOKEN=enketorules
DJANGO_SECRET_KEY=Xyz
KOBO_SUPERUSER_USERNAME=xyz
KOBO_SUPERUSER_PASSWORD=xyz1234
KPI_PUBLIC_PORT=8000
KOBOCAT_PUBLIC_PORT=8001
ENKETO_EXPRESS_PUBLIC_PORT=8005

```

**Comment by abhishekricky** [comment]
I am also receiving same issue. 

@azri by chance were you able to find the root cause ?

**Comment by esmail** [comment]
@azri, you haven't filled out **all** mandatory variables in the `envfile` as is an explicitly-stated step in the README. If you have further issues after following the instructions, pleas let us know.

**Comment by azri** [comment]
Did latest code pull, rebuilt all container images and used below envfile.local.txt file with all variable values. Still it is giving Bad Request (400) error for both http://localhost:8000/ and http://localhost:8001/ 

```
#######################
# Mandatory variables #
#######################

# The address where your KoBo Toolbox instance can be reached.
# NOTE: If you are not connected to a network or don't intend to permit access
#   from other devices on your network, use the IP address of Docker's network
#   interface. This can be obtained e.g with the following command:
#   docker-compose run --rm kpi /sbin/ip route|awk '/default/ { print $3 }'
HOST_ADDRESS=172.17.0.1
# See "api key" here: https://github.com/kobotoolbox/enketo-express/tree/master/config#linked-form-and-data-server
ENKETO_API_TOKEN=enketorules
# Canonically a 50-character random string. See https://docs.djangoproject.com/en/1.8/ref/settings/#secret-key and https://docs.djangoproject.com/en/1.8/ref/settings/#secret-key
DJANGO_SECRET_KEY=Addo
# The initial superuser's username.
KOBO_SUPERUSER_USERNAME=admin
# The initial superuser's password.
KOBO_SUPERUSER_PASSWORD=Addo1234
# NOTE: Any changes to the public ports must also be reflected in the `ports` directives for the `nginx` container in `docker-compose.local.yml`.
KPI_PUBLIC_PORT=8000
KOBOCAT_PUBLIC_PORT=8001
ENKETO_EXPRESS_PUBLIC_PORT=8005

```

I am using Ubuntu 14.10 version.

**Comment by esmail** [comment]
Great; now just use the `HOST_ADDRESS` value you specified instead of `localhost`.

**Comment by azri** [comment]
Thanks @esmall. The instances working with URLs http://172.17.0.1:8000 and http://172.17.0.1:8001. 

Can you please provide more details why the instances did not work with localhost? I always use to do Port forwarding to container and access instances using localhost.

**Comment by esmail** [comment]
If you follow the thread, `${HOST_ADDRESS}` is [assigned to `DJANGO_ALLOWED_HOSTS`](https://github.com/kobotoolbox/kobo-docker/blob/1fcc0d97fc50684f003eda35cca54e9b99a59693/scripts/computed_vars.local.source.bash#L6) then used in [KPI](https://github.com/kobotoolbox/kpi/blob/afd07d8b33258e371b4005a0e63cb764d7d24968/kobo_playground/settings.py#L38) and [KoBoCAT](https://github.com/kobotoolbox/kobocat/blob/e97025a07257f43ef236ccdbab08d0320e53c194/onadata/settings/kc_environ.py#L35) as Django's [`ALLOWED_HOSTS`](https://docs.djangoproject.com/en/1.8/ref/settings/#std:setting-ALLOWED_HOSTS) setting. `ALLOWED_HOSTS` is a security setting, but we also use it to force user to access the site from `${HOST_ADDRESS}` for cookie sharing, etc. between KPI and KC.

**Comment by yeffercardona** [comment]
Buenas tengo un error posterior a ese en el que al previzualizar los formularios en kobotoolbox me sale connect ehostunreach y corri kobotoolbox en primer plano y sale este error 
![2018-05-08](https://user-images.githubusercontent.com/38251649/39817198-1b641840-5363-11e8-966c-700216753010.png)
cual quier ayuda seria de mucho agradecimiento una es en el formulario otra en primer plano en el servidor
![kobo error](https://user-images.githubusercontent.com/38251649/39817199-1b811ea4-5363-11e8-8623-60d336e9f9c3.png)
