### ISSUE TITLE
Create redeployment script for docker

### ISSUE THREAD

**Issue by tinok** [kobotoolbox/kobo-docker#41]

**Comment by GrupoCATO** [comment]
https://github.com/kobotoolbox/kobo-install

**Comment by GrupoCATO** [comment]
https://github.com/GrupoCATO/reverse-proxy-clouddata
https://github.com/GrupoCATO/kobo-docker-clouddata

**Comment by noliveleger** [comment]
https://github.com/kobotoolbox/kobo-install
