### ISSUE TITLE
data export

### ISSUE THREAD

**Issue by iahmedani** [kobotoolbox/kobo-docker#43]
data export to specific format has stopped working, always gives error " 500 Error

If this is a significant error that needs to be fixed, please send a support request to support@kobotoolbox.org with information about what triggered this error."

Please advise

**Comment by hgilberds** [comment]
Data viewing and export has stopped working. Always gives 500 error:

If this is a significant error that needs to be fixed, please send a support request to support@kobotoolbox.org with information about what triggered this error.

Please advise!

**Comment by esmail** [comment]
@hgilberds, I just tested and was able to generate an analyser export without trouble. Do you have any associated output at the command line? Is it possible your `kobo-docker` code or images are out of date?

**Comment by hgilberds** [comment]
Hello, thank-you! Kobo informed me that their server was experiencing some
problems with data retrieval for 2 days, but it is fixed now!

**Comment by esmail** [comment]
Glad to hear it's working for you now :)
