### ISSUE TITLE
Delete old images from Docker Hub.

### ISSUE THREAD

**Issue by esmail** [kobotoolbox/kobo-docker#45]
Currently:
https://hub.docker.com/r/kobotoolbox/psql/: 1.1K pulls
https://hub.docker.com/r/kobotoolbox/dkobo/: 240 pulls (pending deprecation of `dkobo`)
https://hub.docker.com/r/kobotoolbox/base-psql/: 239 pulls
https://hub.docker.com/r/kobotoolbox/base-dkobo/: 175 pulls

**Comment by esmail** [comment]
Now:
https://hub.docker.com/r/kobotoolbox/psql/: 1.2K pulls
https://hub.docker.com/r/kobotoolbox/dkobo/: 278 pulls (pending deprecation of `dkobo`)
https://hub.docker.com/r/kobotoolbox/base-psql/: 263 pulls
https://hub.docker.com/r/kobotoolbox/base-dkobo/: 205 pulls

**Comment by noliveleger** [comment]
@jnm can you do the clean-up? And close this issue when (or if it's already) done

**Comment by jnm** [comment]
@noliveleger, I just trashed a couple old ones that hadn't been updated in years, but are we safe to delete the old database images, i.e. the ones that we've replaced with community-maintained versions? We have to be sure they're not still used anywhere. Unfortunately, I can't see where Docker Hub shows how frequently the images are downloaded, only the total count.

Also, do you need access to our Docker Hub organization?

**Comment by noliveleger** [comment]
@jnm Actually I already have access.
