### ISSUE TITLE
Run EE in a subdirectory

### ISSUE THREAD

**Issue by esmail** [kobotoolbox/kobo-docker#5]

**Comment by esmail** [comment]
E.g. http://localhost/enketo-express

**Comment by esmail** [comment]
Having everything running under one domain/subdomain would facilitate using server setups using single certificates (apparently wildcard certs. are [wildly](https://www.digicert.com/easy-csr/openssl.htm) more expensive) and free certs. from [Let's Encrypt](https://letsencrypt.org/).

**Comment by rhunwicks** [comment]
See https://github.com/kobotoolbox/kpi/issues/1041

**Comment by rhunwicks** [comment]
And see https://github.com/kobotoolbox/kobocat/issues/298

**Comment by noliveleger** [comment]
Wildcard SSL certificates are available with Let's Encrypt. 
With `kobo-install`, it's not an hassle anymore.
