### ISSUE TITLE
Create configuration for disable django email activation for local server

### ISSUE THREAD

**Issue by vozhyk-com** [kobotoolbox/kobo-docker#50]
Looks like no possibility to use local server and add new users without Internet.
Will be good to have some setting in envfile.local.txt for disable django email activation for new user registration.

**Comment by noliveleger** [comment]
@vozhyk-com, Good idea. 
Unfortunately, we have our hands full as the core team and cannot provide much support for individual requests.
Feel free to create pull requests in related repositories.
Be aware that structure has changed.
