### ISSUE TITLE
Getting 'Error 500'  for  'view data in table' or  'analyse data'  in Kobocat

### ISSUE THREAD

**Issue by addoinc** [kobotoolbox/kobo-docker#60]
Can't see form submission data in kobocat, upon clicking 'view data in table' or  'analyse data' links I am getting 500 error.

**Comment by ferminarellano** [comment]
I have this problem as well. I installed kobo-docker on a public server, it has all the certs.  And everything seems to be working fine, the only problem was when I uploaded some form definition and data with ODK Briefcase. Data is shown in Kobocat but not in KPI, and when I try to 'view data in table' or 'analyse data' links im getting a 500 error.

**Comment by veekrum** [comment]
i am getting same error as well. can anyone help??

**Comment by noliveleger** [comment]
This issue seemed to be related to `kpi`. 
Ticket closed due to inactivity.
Please visit https://community.kobotoolbox.org/ for help.
