### ISSUE TITLE
getting error 504

### ISSUE THREAD

**Issue by allankaranja** [kobotoolbox/kobo-docker#61]
Hi..
I have successfully deployed kobo-docker in an ubuntu vm in google cloud engine..when I try to connect through the internal ip i get a 504 error.Kindly assist...my machine is running on ubuntu 14..The logs seems to be right

**Comment by noliveleger** [comment]
Ticket closed due to inactivity.
Have a look at https://github.com/kobotoolbox/kobo-install
Please visit https://community.kobotoolbox.org/ for help.
