### ISSUE TITLE
Form Builder resets options

### ISSUE THREAD

**Issue by vladimir-spintech** [kobotoolbox/kobo-docker#63]
1. Create a form
2. Add a 'Select One' question
3. Change the default values for the options
4. Click Save
5. Close Form
6. Click Edit in Form Builder

Result: The options values are reset to default (Option 1 and Option 2)

Note: The values in DB are correct, it is something with displaying.

**Comment by jnm** [comment]
Must've been fixed in the the intervening years. Cannot reproduce.
