### ISSUE TITLE
It's my first time to use Docker

### ISSUE THREAD

**Issue by maelfosso** [kobotoolbox/kobo-docker#64]
Hi everybody,

I would like to use Kobo. I follow the procedure up to `docker-compose up`
The problem is I get `502 Bad Gateway` when I try to access to Kobo via `http://172.17.0.1:8000`

My console display many things I don't understand. I just see some word like `enketo`, `redis`, `mongo`, etc.. and some url `172.17.0.7`,  `172.17.0.9` and others 
I don't know why It's not working and How to solve the problem.

Please, Could someone give some indications ?

**Comment by maelfosso** [comment]
Just to say that I'm on Ubuntu 16.04 and always use `sudo`

**Comment by maelfosso** [comment]
How to know if everything is ok and I could just start use it ?

**Comment by esmail** [comment]
Per #65, it seems you were able to get beyond this.
