### ISSUE TITLE
HOST_ADDRESS

### ISSUE THREAD

**Issue by maelfosso** [kobotoolbox/kobo-docker#65]
Hi,

Please how to set the HOST_ADDRESS variable to access to KoboToolbox from any computer connected to the local network ?
In fact, I set the HOST_ADDRESS variable at 192.168.0.158 but I got an error everytime I try to access to KoboToolbox from this ip address.

How to set it please ?

**Comment by esmail** [comment]
Apologies for the delayed response. The `envfile` and main README now have more detailed information on how the settings should be configured and where to access your server once it's running.

**Comment by maelfosso** [comment]
Thanks for answering.
I set the HOST_ADDRESS with the IP Address of the computer hosting Kobo-docker in local mode (192.168.3.100). With That everyone in the local network could access to the server.
 
After that the IT Department has tried to make Kobo-docker  accessible remotely by using NAT and IPTABLES without success. I don't know where is the problem.

Is it Docker the problem or Kobo ? How to solve this problem such that people can send data to the server using smartphone ?

Thanks.

**Comment by esmail** [comment]
Glad to hear you were able to get `kobo-docker` working locally. Unfortunately we don't have the capacity to troubleshoot your particular network environment.

Please note that if you're planning on allowing connections from the internet, we strongly recommend not using the *local* setup but rather using the *server* setup, which uses HTTPS to secure communications. This would also simplify some issues relating to the *local* setup receiving connections on 3 separate ports.
