### ISSUE TITLE
Error geting blank form form the kobo tool box

### ISSUE THREAD

**Issue by sushantinfo4u** [kobotoolbox/kobo-docker#66]
I configured the local kobo tool box server 
URL:http://192.168.2.148:8016
Username:kobo
Server is working properly but in the kobo collect geting the blank form shows error
"Form Not Found" 
App configuration URL:http://192.168.2.148 uname:kobo pass:****

**Comment by esmail** [comment]
Apologies for the delayed response. It sounds like Collect was able to connect to the server (you can confirm this by navigating to the URL in a browser on the same device), but it's possible you hadn't clicked to "deploy" any forms yet.
