### ISSUE TITLE
Add `dhparam` requirement and instructions

### ISSUE THREAD

**Issue by esmail** [kobotoolbox/kobo-docker#70]

**Comment by CharleyPeng1** [comment]
I ran the command `openssl dhparam -out /etc/ssl/dhparams.pem 2048` and added `ssl_dhparam /etc/ssl/dhparams.pem;` within the server block.

Let me know if you want me to add that to a script + template for you.

**Comment by esmail** [comment]
@CharleyPeng1, thanks for raising this issue; as you can see, it's been on my todo list for some time and a PR would be most welcome. I'd like to do this inside the `nginx` container so there aren't any new dependencies on the host environment. So maybe a short `bash` script that we could run at initialization time that looks for the `dhparam` file and generates one if it isn't found.

**Comment by esmail** [comment]
Alternatively, it seems like Mozilla recommends using a pre-defined Diffie-Hellman groups: https://wiki.mozilla.org/Security/Server_Side_TLS#Pre-defined_DHE_groups

**Comment by CharleyPeng1** [comment]
I'm not familiar enough with this to make the call. I prefer generating them myself, for no real reason, it does mean initial build will be slower.

**Comment by noliveleger** [comment]
`kobo-install` is now highly recommended for new installations. 
It also uses `Let'sEncrypt` for SSL certificates and handles the installation automatically.
