### ISSUE TITLE
Version compatible - Linux

### ISSUE THREAD

**Issue by thiagoemanoel1992** [kobotoolbox/kobo-docker#75]
Hi all friends , 

Could i install Kobotool at Linux 12.04 ?

**Comment by esmail** [comment]
The only strict requirement is that you be able to install 64-bit Docker Compose for Linux, so please check the Docker documentation we've linked to for information about what platforms they support and installation instructions. FYI, our team has mostly run `kobo-docker` on Ubuntu 14.04 and 16.04.

**Comment by ksamuel** [comment]
Bonjour,

Je suis en déplacement et injoignable jusqu'au 27 novembre.

Cordialement,

Kevin

--

Hi,

I'm on a trip and can't be reached until Novembre, the 27th.

Regards,

Kevin
