### ISSUE TITLE
User Permision

### ISSUE THREAD

**Issue by iahmedani** [kobotoolbox/kobo-docker#77]
Hi Team,

With reference to below article 
http://support.kobotoolbox.org/customer/portal/articles/2103898-managing-permissions 
I have tried alot to manage other datacollector (other users) to get forms and submit their response but unfortuenatly it is not working.

Please advise.

Best Wishes, Imran Ahmedani

**Comment by esmail** [comment]
Imran. Is this the same problem you reported in your other issue?
https://github.com/kobotoolbox/kobo-docker/issues/78

**Comment by iahmedani** [comment]
Yes, further to add in it, would it be possible to add user management
module for permission or create teams?

**Comment by noliveleger** [comment]
Ticket closed due to inactivity. 
Please visit https://community.kobotoolbox.org/ for help.
