### ISSUE TITLE
Enketo requires HTTPS on HTTP-only local instance of KoBo Toolbox

### ISSUE THREAD

**Issue by iahmedani** [kobotoolbox/kobo-docker#78]
Hi Team,

I am using kobo-docker, I have deployed a server on http protocol, whenever I enable 'Require authentication to see forms and submit data' and try to access through webform it gives me below error.
Forbidden. Enketo needs to use https in production mode to enable authentication.

Need your urgent support.

With Kind Regards, Imran Ahmedani

**Comment by esmail** [comment]
Hi, Imran. For testing, you can edit the [Enketo configuration](https://github.com/kobotoolbox/kobo-docker/blob/master/enketo_express/config.json) to set the [`authentication -> allow insecure transport` mode to `true`](https://github.com/kobotoolbox/enketo-express/tree/master/config), but this is strongly discouraged for any other purposes as it means you will be transmitting credentials unencrypted.

On a related note, we happen to be exploring the possibility of getting KoBo to run on a single hostname, which would facilitate getting free `letsencrypt` SSL key+cert. pairs and using HTTPS, but I can't yet estimate how long this might take.

**Comment by iahmedani** [comment]
Many thanks esmail,

I'm talking about docker where when I add more linke enketo service never starts. plz help

**Comment by esmail** [comment]
If Enketo won't load after you edited the file, it's most likely because your changes didn't result the file contents being valid JSON. The starting point for investigating errors is always `docker-compose logs -f`.
