### ISSUE TITLE
Dataset Filter

### ISSUE THREAD

**Issue by iahmedani** [kobotoolbox/kobo-docker#80]
Hi team,

Would it be possible to have dataset filter as one site is offering.

Filter question to view and set criteria over one or multiple variables to specify map or analysis to those selected variables instead of all data?

**Comment by iahmedani** [comment]
I have found one view in kobocat which can be utilized with above my request, 

> http://server:8001/user/forms/formname/view-data

Please look into it.

**Comment by noliveleger** [comment]
Unfortunately, we have our hands full as the core team and cannot provide much support for individual requests. 
You can still submit pull requests to respective repositories.

Otherwise, please visit https://community.kobotoolbox.org/ for help.
