### ISSUE TITLE
Superuser single quote escaping issue: "I'm Batman"

### ISSUE THREAD

**Issue by jnm** [kobotoolbox/kobo-docker#81]
When setting `KOBO_SUPERUSER_USERNAME` or `KOBO_SUPERUSER_PASSWORD` to a value that contains a single quote, e.g. `i'm batman`, [the shell script that constructs a Python snippet and pipes it to `./manage.py shell`](https://github.com/kobotoolbox/kobo-docker/blob/532e808706b61deff269dfdfc71781e0086f6124/scripts/create_kobo_superuser.bash#L8) fails.

**Comment by p2edwards** [comment]
I think I know how to fix it.
