### ISSUE TITLE
User Permissions - Can Edit

### ISSUE THREAD

**Issue by iahmedani** [kobotoolbox/kobo-docker#91]
Hi Team,

Would it be possible, user with permission  "Can Edit" could only edit instance and can't delete it?

Regards,
Imran Ahmedani

**Comment by esmail** [comment]
Hi, Imran. It's unlikely that we'll modify this behaviour. If you'd like to code up a solution yourself, you can make a pull request into the repository where the relevant code exists, [kobocat](https://github.com/kobotoolbox/kobocat).
