### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by bunnybooboo** [kobotoolbox/kobo-docker#93]
Volunteer here testing MSF site and coming into this repo as most complete reflecting site.
After creating new DRAFT form, saving, X'ing out >> can not select draft forms. Stuck in loop. URL appropriately changes, so if I refresh page it loads as expected.

Chrome - Uncaught TypeError: Cannot read property 'username' of undefined 
Firefox - TypeError: this.state.currentAccount is undefined

**Comment by esmail** [comment]
This has been fixed [here](https://github.com/kobotoolbox/kpi/pull/1075/commits/11dabb4c828dcc717d110c7307a72ef1eb4d68ae) in the [`kpi`](https://github.com/kobotoolbox/kpi) repo. The MSF `kpi` will need to be redeployed for the change to take effect.
