### ISSUE TITLE
Update `dockerize`.

### ISSUE THREAD

**Issue by esmail** [kobotoolbox/kobo-docker#94]
Currently-used version is fairly old and appears to use spinlocks (high CPU utilization).

**Comment by esmail** [comment]
[Current](https://github.com/jwilder/dockerize) is up to v0.3.0; [we're using v0.2.0](https://github.com/kobotoolbox/kobo-docker/blob/0776399fbfe3a78787cfe5a9023f86e96a4504ef/base_images/base-kobos/Dockerfile#L31)

**Comment by jnm** [comment]
We should actually do this

**Comment by jnm** [comment]
Additionally—if indeed it's `dockerize` who's responsible for it—this timeout needs to be increased: `Timeout after 1m0s waiting on dependencies to become available: [tcp://kpi:8000]`. It sits there looping while KPI builds static files etc.
