### ISSUE TITLE
Fix RabbitMQ connection error for KoboCat

### ISSUE THREAD

**Issue by pmusaraj** [kobotoolbox/kobo-docker#96]
Using Docker for Mac, I get this RabbitMQ connection error for KoboCat: 

    [2017-01-25 11:05:38,961: ERROR/MainProcess] consumer: Cannot connect to amqp://kobocat:**@rabbit:5672/kobocat: Couldn't log in: a socket error occurred.

I did get this working by doing the following: 

1. Added kobocat user inside the rabbit image 

Log into rabbit image using `docker exec -it kobodocker_rabbit_1 bash` and then
`rabbitmqctl add_user kobocat kobocat`
`rabbitmqctl set_user_tags kobocat administrator`
`rabbitmqctl set_permissions -p / kobocat ".*" ".*" ".*"`

2. In `envfiles/kobocat.txt` set this: `KOBOCAT_BROKER_URL=amqp://kobocat:kobocat@rabbit:5672/`

**Comment by noliveleger** [comment]
RabbitMQ is not used anymore.
