### ISSUE TITLE
enketo_express not working

### ISSUE THREAD

**Issue by iahmedani** [kobotoolbox/kobo-docker#99]
few moments ago  I updated kobo-docker, and made changes where required. but now enketo doesn't starts.

please look into it.

`/etc/my_init.d/01_setup_enketo.bash: line 12:    12 Segmentation fault      (core dumped) grunt
enketo_express_1  | *** /etc/my_init.d/01_setup_enketo.bash failed with status 139
enketo_express_1  |
enketo_express_1  | *** Killing all processes...
`

**Comment by esmail** [comment]
Same here.

@MartijnR, getting the following error when running `grunt` for Enketo initialization:
```
...
enketo_express_1 | Running "sass:compile" (sass) task
enketo_express_1 | >> Error: File to import not found or unreadable: ../../../../../node_modules/bootstrap-datepicker/dist/css/bootstrap-datepicker.
enketo_express_1 | >> Parent style sheet: /srv/src/enketo_express/node_modules/enketo-core/src/widget/date/datepicker-extended.scss
enketo_express_1 | >> on line 1 of node_modules/enketo-core/src/widget/date/datepicker-extended.scss
enketo_express_1 | >> >> @import "../../../../../node_modules/bootstrap-datepicker/dist/css/bootstrap-d
enketo_express_1 | >> ^
enketo_express_1 | Warning: Use --force to continue.
enketo_express_1 |
enketo_express_1 | Aborted due to warnings.
...
```
BTW, any interest in adding a plain `grunt` (with a dummy `config.json` if necessary) to Travis to test e.g. this issue?

**Comment by MartijnR** [comment]
I think it might be the recent change to [drop npm 2 support](https://github.com/kobotoolbox/enketo-express/blob/master/CHANGELOG.md#1370---2016-01-25) (also notified [here](https://groups.google.com/forum/#!topic/enketo-users/eG9tAKa046c) - subscribe! :) ).

That was a deliberate break, so I actually removed npm2 from Travis.

While you're at it, you may also want to start using node 6.x (as older node versions will break next).

**Comment by esmail** [comment]
Thanks for the info; the fix was as [easy](https://github.com/kobotoolbox/enketo-express/pull/638/commits/92ccefcfb5c8be8f32c79a73774598d8e94b41a1) as they come :)

P.S. I see that the `sass:compile` build step is, in fact, [already](https://travis-ci.org/kobotoolbox/enketo-express/jobs/198204250#L2711) part of your Travis tests.

**Comment by esmail** [comment]
@iahmedani, this is now fixed and an [updated image](https://hub.docker.com/r/kobotoolbox/enketo_express/builds/) should be ready to pull shortly. Also, please contact me by e-mail or at support@kobotoolbox.org to discuss another matter.
